/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum BrandRegistrationsEnumIdentityStatus {
    SELF_DECLARED("SELF_DECLARED"),
    UNVERIFIED("UNVERIFIED"),
    VERIFIED("VERIFIED"),
    VETTED_VERIFIED("VETTED_VERIFIED");

    @JsonValue
    public final String value;

    private BrandRegistrationsEnumIdentityStatus(String value) {
        this.value = value;
    }
}
