/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * BrandVettingEnumVettingProvider - The third-party provider of the vettings to read
 */
public enum BrandVettingEnumVettingProvider {
    CAMPAIGN_VERIFY("campaign-verify");

    @JsonValue
    public final String value;

    private BrandVettingEnumVettingProvider(String value) {
        this.value = value;
    }
}
