/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum BrandRegistrationsEnumStatus {
    PENDING("PENDING"),
    APPROVED("APPROVED"),
    FAILED("FAILED"),
    IN_REVIEW("IN_REVIEW"),
    DELETED("DELETED");

    @JsonValue
    public final String value;

    private BrandRegistrationsEnumStatus(String value) {
        this.value = value;
    }
}
