/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MessagingV1ServiceFallbackMethod - The HTTP method we use to call `fallback_url`. Can be: `GET` or `POST`.
 */
public enum MessagingV1ServiceFallbackMethod {
    HEAD("HEAD"),
    GET("GET"),
    POST("POST"),
    PATCH("PATCH"),
    PUT("PUT"),
    DELETE("DELETE");

    @JsonValue
    public final String value;

    private MessagingV1ServiceFallbackMethod(String value) {
        this.value = value;
    }
}
