/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.shared;




public class MessagingV1BrandRegistrationsLinks {
    public MessagingV1BrandRegistrationsLinks(){}
}
