/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * MessagingV1BrandRegistrationsBrandRegistrationOtp - Created
 */

public class MessagingV1BrandRegistrationsBrandRegistrationOtp {
    /**
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Brand Registration resource.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("account_sid")
    public String accountSid;

    public MessagingV1BrandRegistrationsBrandRegistrationOtp withAccountSid(String accountSid) {
        this.accountSid = accountSid;
        return this;
    }
    
    /**
     * The unique string to identify Brand Registration of Sole Proprietor Brand
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("brand_registration_sid")
    public String brandRegistrationSid;

    public MessagingV1BrandRegistrationsBrandRegistrationOtp withBrandRegistrationSid(String brandRegistrationSid) {
        this.brandRegistrationSid = brandRegistrationSid;
        return this;
    }
    
    public MessagingV1BrandRegistrationsBrandRegistrationOtp(){}
}
