/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * MessagingV1Deactivation - Temporary Redirect
 */

public class MessagingV1Deactivation {
    /**
     * Returns an authenticated url that redirects to a file containing the deactivated numbers for the requested day. This url is valid for up to two minutes.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("redirect_to")
    public String redirectTo;

    public MessagingV1Deactivation withRedirectTo(String redirectTo) {
        this.redirectTo = redirectTo;
        return this;
    }
    
    public MessagingV1Deactivation(){}
}
