/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * MessagingV1Usecase - OK
 */

public class MessagingV1Usecase {
    /**
     * Human readable use case details (usecase, description and purpose) of Messaging Service Use Cases.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("usecases")
    public Object[] usecases;

    public MessagingV1Usecase withUsecases(Object[] usecases) {
        this.usecases = usecases;
        return this;
    }
    
    public MessagingV1Usecase(){}
}
