/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.shared;



/**
 * MessagingV1ServiceLinks - The absolute URLs of related resources.
 */

public class MessagingV1ServiceLinks {
    public MessagingV1ServiceLinks(){}
}
