/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.shared;

import circl_dev.twilio_messaging.utils.DateTimeDeserializer;
import circl_dev.twilio_messaging.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

/**
 * MessagingV1TollfreeVerification - Created
 */

public class MessagingV1TollfreeVerification {
    /**
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Tollfree Verification resource.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("account_sid")
    public String accountSid;

    public MessagingV1TollfreeVerification withAccountSid(String accountSid) {
        this.accountSid = accountSid;
        return this;
    }
    
    /**
     * Additional information to be provided for verification.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("additional_information")
    public String additionalInformation;

    public MessagingV1TollfreeVerification withAdditionalInformation(String additionalInformation) {
        this.additionalInformation = additionalInformation;
        return this;
    }
    
    /**
     * The city of the business or organization using the Tollfree number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("business_city")
    public String businessCity;

    public MessagingV1TollfreeVerification withBusinessCity(String businessCity) {
        this.businessCity = businessCity;
        return this;
    }
    
    /**
     * The email address of the contact for the business or organization using the Tollfree number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("business_contact_email")
    public String businessContactEmail;

    public MessagingV1TollfreeVerification withBusinessContactEmail(String businessContactEmail) {
        this.businessContactEmail = businessContactEmail;
        return this;
    }
    
    /**
     * The first name of the contact for the business or organization using the Tollfree number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("business_contact_first_name")
    public String businessContactFirstName;

    public MessagingV1TollfreeVerification withBusinessContactFirstName(String businessContactFirstName) {
        this.businessContactFirstName = businessContactFirstName;
        return this;
    }
    
    /**
     * The last name of the contact for the business or organization using the Tollfree number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("business_contact_last_name")
    public String businessContactLastName;

    public MessagingV1TollfreeVerification withBusinessContactLastName(String businessContactLastName) {
        this.businessContactLastName = businessContactLastName;
        return this;
    }
    
    /**
     * The phone number of the contact for the business or organization using the Tollfree number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("business_contact_phone")
    public String businessContactPhone;

    public MessagingV1TollfreeVerification withBusinessContactPhone(String businessContactPhone) {
        this.businessContactPhone = businessContactPhone;
        return this;
    }
    
    /**
     * The country of the business or organization using the Tollfree number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("business_country")
    public String businessCountry;

    public MessagingV1TollfreeVerification withBusinessCountry(String businessCountry) {
        this.businessCountry = businessCountry;
        return this;
    }
    
    /**
     * The name of the business or organization using the Tollfree number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("business_name")
    public String businessName;

    public MessagingV1TollfreeVerification withBusinessName(String businessName) {
        this.businessName = businessName;
        return this;
    }
    
    /**
     * The postal code of the business or organization using the Tollfree number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("business_postal_code")
    public String businessPostalCode;

    public MessagingV1TollfreeVerification withBusinessPostalCode(String businessPostalCode) {
        this.businessPostalCode = businessPostalCode;
        return this;
    }
    
    /**
     * The state/province/region of the business or organization using the Tollfree number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("business_state_province_region")
    public String businessStateProvinceRegion;

    public MessagingV1TollfreeVerification withBusinessStateProvinceRegion(String businessStateProvinceRegion) {
        this.businessStateProvinceRegion = businessStateProvinceRegion;
        return this;
    }
    
    /**
     * The address of the business or organization using the Tollfree number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("business_street_address")
    public String businessStreetAddress;

    public MessagingV1TollfreeVerification withBusinessStreetAddress(String businessStreetAddress) {
        this.businessStreetAddress = businessStreetAddress;
        return this;
    }
    
    /**
     * The address of the business or organization using the Tollfree number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("business_street_address2")
    public String businessStreetAddress2;

    public MessagingV1TollfreeVerification withBusinessStreetAddress2(String businessStreetAddress2) {
        this.businessStreetAddress2 = businessStreetAddress2;
        return this;
    }
    
    /**
     * The website of the business or organization using the Tollfree number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("business_website")
    public String businessWebsite;

    public MessagingV1TollfreeVerification withBusinessWebsite(String businessWebsite) {
        this.businessWebsite = businessWebsite;
        return this;
    }
    
    /**
     * Customer's Profile Bundle BundleSid.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("customer_profile_sid")
    public String customerProfileSid;

    public MessagingV1TollfreeVerification withCustomerProfileSid(String customerProfileSid) {
        this.customerProfileSid = customerProfileSid;
        return this;
    }
    
    /**
     * The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("date_created")
    public OffsetDateTime dateCreated;

    public MessagingV1TollfreeVerification withDateCreated(OffsetDateTime dateCreated) {
        this.dateCreated = dateCreated;
        return this;
    }
    
    /**
     * The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("date_updated")
    public OffsetDateTime dateUpdated;

    public MessagingV1TollfreeVerification withDateUpdated(OffsetDateTime dateUpdated) {
        this.dateUpdated = dateUpdated;
        return this;
    }
    
    /**
     * The date and time when the ability to edit a rejected verification expires.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("edit_expiration")
    public OffsetDateTime editExpiration;

    public MessagingV1TollfreeVerification withEditExpiration(OffsetDateTime editExpiration) {
        this.editExpiration = editExpiration;
        return this;
    }
    
    /**
     * The error code given when a Tollfree Verification has been rejected.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("error_code")
    public Long errorCode;

    public MessagingV1TollfreeVerification withErrorCode(Long errorCode) {
        this.errorCode = errorCode;
        return this;
    }
    
    /**
     * An optional external reference ID supplied by customer and echoed back on status retrieval.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("external_reference_id")
    public String externalReferenceId;

    public MessagingV1TollfreeVerification withExternalReferenceId(String externalReferenceId) {
        this.externalReferenceId = externalReferenceId;
        return this;
    }
    
    /**
     * Estimate monthly volume of messages from the Tollfree Number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("message_volume")
    public String messageVolume;

    public MessagingV1TollfreeVerification withMessageVolume(String messageVolume) {
        this.messageVolume = messageVolume;
        return this;
    }
    
    /**
     * The email address to receive the notification about the verification result. .
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("notification_email")
    public String notificationEmail;

    public MessagingV1TollfreeVerification withNotificationEmail(String notificationEmail) {
        this.notificationEmail = notificationEmail;
        return this;
    }
    
    /**
     * Link to an image that shows the opt-in workflow. Multiple images allowed and must be a publicly hosted URL.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("opt_in_image_urls")
    public String[] optInImageUrls;

    public MessagingV1TollfreeVerification withOptInImageUrls(String[] optInImageUrls) {
        this.optInImageUrls = optInImageUrls;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("opt_in_type")
    public TollfreeVerificationEnumOptInType optInType;

    public MessagingV1TollfreeVerification withOptInType(TollfreeVerificationEnumOptInType optInType) {
        this.optInType = optInType;
        return this;
    }
    
    /**
     * An example of message content, i.e. a sample message.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("production_message_sample")
    public String productionMessageSample;

    public MessagingV1TollfreeVerification withProductionMessageSample(String productionMessageSample) {
        this.productionMessageSample = productionMessageSample;
        return this;
    }
    
    /**
     * The SID of the Regulated Item.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("regulated_item_sid")
    public String regulatedItemSid;

    public MessagingV1TollfreeVerification withRegulatedItemSid(String regulatedItemSid) {
        this.regulatedItemSid = regulatedItemSid;
        return this;
    }
    
    /**
     * The rejection reason given when a Tollfree Verification has been rejected.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("rejection_reason")
    public String rejectionReason;

    public MessagingV1TollfreeVerification withRejectionReason(String rejectionReason) {
        this.rejectionReason = rejectionReason;
        return this;
    }
    
    /**
     * The URLs of the documents associated with the Tollfree Verification resource.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("resource_links")
    public Object resourceLinks;

    public MessagingV1TollfreeVerification withResourceLinks(Object resourceLinks) {
        this.resourceLinks = resourceLinks;
        return this;
    }
    
    /**
     * The unique string to identify Tollfree Verification.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sid")
    public String sid;

    public MessagingV1TollfreeVerification withSid(String sid) {
        this.sid = sid;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    public TollfreeVerificationEnumStatus status;

    public MessagingV1TollfreeVerification withStatus(TollfreeVerificationEnumStatus status) {
        this.status = status;
        return this;
    }
    
    /**
     * The SID of the Phone Number associated with the Tollfree Verification.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tollfree_phone_number_sid")
    public String tollfreePhoneNumberSid;

    public MessagingV1TollfreeVerification withTollfreePhoneNumberSid(String tollfreePhoneNumberSid) {
        this.tollfreePhoneNumberSid = tollfreePhoneNumberSid;
        return this;
    }
    
    /**
     * Tollfree TrustProduct Bundle BundleSid.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("trust_product_sid")
    public String trustProductSid;

    public MessagingV1TollfreeVerification withTrustProductSid(String trustProductSid) {
        this.trustProductSid = trustProductSid;
        return this;
    }
    
    /**
     * The absolute URL of the Tollfree Verification resource.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("url")
    public String url;

    public MessagingV1TollfreeVerification withUrl(String url) {
        this.url = url;
        return this;
    }
    
    /**
     * The category of the use case for the Tollfree Number. List as many are applicable..
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("use_case_categories")
    public String[] useCaseCategories;

    public MessagingV1TollfreeVerification withUseCaseCategories(String[] useCaseCategories) {
        this.useCaseCategories = useCaseCategories;
        return this;
    }
    
    /**
     * Use this to further explain how messaging is used by the business or organization.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("use_case_summary")
    public String useCaseSummary;

    public MessagingV1TollfreeVerification withUseCaseSummary(String useCaseSummary) {
        this.useCaseSummary = useCaseSummary;
        return this;
    }
    
    public MessagingV1TollfreeVerification(){}
}
