/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.shared;

import circl_dev.twilio_messaging.utils.DateTimeDeserializer;
import circl_dev.twilio_messaging.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

/**
 * MessagingV1BrandRegistrationsBrandVetting - Created
 */

public class MessagingV1BrandRegistrationsBrandVetting {
    /**
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the vetting record.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("account_sid")
    public String accountSid;

    public MessagingV1BrandRegistrationsBrandVetting withAccountSid(String accountSid) {
        this.accountSid = accountSid;
        return this;
    }
    
    /**
     * The unique string to identify Brand Registration.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("brand_sid")
    public String brandSid;

    public MessagingV1BrandRegistrationsBrandVetting withBrandSid(String brandSid) {
        this.brandSid = brandSid;
        return this;
    }
    
    /**
     * The Twilio SID of the third-party vetting record.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("brand_vetting_sid")
    public String brandVettingSid;

    public MessagingV1BrandRegistrationsBrandVetting withBrandVettingSid(String brandVettingSid) {
        this.brandVettingSid = brandVettingSid;
        return this;
    }
    
    /**
     * The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("date_created")
    public OffsetDateTime dateCreated;

    public MessagingV1BrandRegistrationsBrandVetting withDateCreated(OffsetDateTime dateCreated) {
        this.dateCreated = dateCreated;
        return this;
    }
    
    /**
     * The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("date_updated")
    public OffsetDateTime dateUpdated;

    public MessagingV1BrandRegistrationsBrandVetting withDateUpdated(OffsetDateTime dateUpdated) {
        this.dateUpdated = dateUpdated;
        return this;
    }
    
    /**
     * The absolute URL of the Brand Vetting resource.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("url")
    public String url;

    public MessagingV1BrandRegistrationsBrandVetting withUrl(String url) {
        this.url = url;
        return this;
    }
    
    /**
     * The type of vetting that has been conducted. One of “STANDARD” (Aegis) or “POLITICAL” (Campaign Verify).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("vetting_class")
    public String vettingClass;

    public MessagingV1BrandRegistrationsBrandVetting withVettingClass(String vettingClass) {
        this.vettingClass = vettingClass;
        return this;
    }
    
    /**
     * The unique identifier of the vetting from the third-party provider.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("vetting_id")
    public String vettingId;

    public MessagingV1BrandRegistrationsBrandVetting withVettingId(String vettingId) {
        this.vettingId = vettingId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("vetting_provider")
    public BrandVettingEnumVettingProvider vettingProvider;

    public MessagingV1BrandRegistrationsBrandVetting withVettingProvider(BrandVettingEnumVettingProvider vettingProvider) {
        this.vettingProvider = vettingProvider;
        return this;
    }
    
    /**
     * The status of the import vetting attempt. One of “PENDING,” “SUCCESS,” or “FAILED”.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("vetting_status")
    public String vettingStatus;

    public MessagingV1BrandRegistrationsBrandVetting withVettingStatus(String vettingStatus) {
        this.vettingStatus = vettingStatus;
        return this;
    }
    
    public MessagingV1BrandRegistrationsBrandVetting(){}
}
