/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ServiceEnumScanMessageContent {
    INHERIT("inherit"),
    ENABLE("enable"),
    DISABLE("disable");

    @JsonValue
    public final String value;

    private ServiceEnumScanMessageContent(String value) {
        this.value = value;
    }
}
