/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * TollfreeVerificationEnumStatus - The compliance status of the Tollfree Verification record.
 */
public enum TollfreeVerificationEnumStatus {
    PENDING_REVIEW("PENDING_REVIEW"),
    IN_REVIEW("IN_REVIEW"),
    TWILIO_APPROVED("TWILIO_APPROVED"),
    TWILIO_REJECTED("TWILIO_REJECTED");

    @JsonValue
    public final String value;

    private TollfreeVerificationEnumStatus(String value) {
        this.value = value;
    }
}
