/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import circl_dev.twilio_messaging.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CreateBrandVettingCreateBrandVettingRequest {
    /**
     * The unique ID of the vetting
     */
    @SpeakeasyMetadata("form:name=VettingId")
    public String vettingId;

    public CreateBrandVettingCreateBrandVettingRequest withVettingId(String vettingId) {
        this.vettingId = vettingId;
        return this;
    }
    
    @SpeakeasyMetadata("form:name=VettingProvider")
    public circl_dev.twilio_messaging.models.shared.BrandVettingEnumVettingProvider vettingProvider;

    public CreateBrandVettingCreateBrandVettingRequest withVettingProvider(circl_dev.twilio_messaging.models.shared.BrandVettingEnumVettingProvider vettingProvider) {
        this.vettingProvider = vettingProvider;
        return this;
    }
    
    public CreateBrandVettingCreateBrandVettingRequest(@JsonProperty("VettingProvider") circl_dev.twilio_messaging.models.shared.BrandVettingEnumVettingProvider vettingProvider) {
        this.vettingProvider = vettingProvider;
  }
}
