/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import circl_dev.twilio_messaging.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CreateShortCodeCreateShortCodeRequest {
    /**
     * The SID of the ShortCode resource being added to the Service.
     */
    @SpeakeasyMetadata("form:name=ShortCodeSid")
    public String shortCodeSid;

    public CreateShortCodeCreateShortCodeRequest withShortCodeSid(String shortCodeSid) {
        this.shortCodeSid = shortCodeSid;
        return this;
    }
    
    public CreateShortCodeCreateShortCodeRequest(@JsonProperty("ShortCodeSid") String shortCodeSid) {
        this.shortCodeSid = shortCodeSid;
  }
}
