/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreateServiceCreateServiceRequestFallbackMethod - The HTTP method we should use to call `fallback_url`. Can be: `GET` or `POST`.
 */
public enum CreateServiceCreateServiceRequestFallbackMethod {
    HEAD("HEAD"),
    GET("GET"),
    POST("POST"),
    PATCH("PATCH"),
    PUT("PUT"),
    DELETE("DELETE");

    @JsonValue
    public final String value;

    private CreateServiceCreateServiceRequestFallbackMethod(String value) {
        this.value = value;
    }
}
