/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import circl_dev.twilio_messaging.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CreateLinkshorteningMessagingServiceRequest {
    /**
     * The domain SID to associate with a messaging service. With URL shortening enabled, links in messages sent with the associated messaging service will be shortened to the provided domain
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=DomainSid")
    public String domainSid;

    public CreateLinkshorteningMessagingServiceRequest withDomainSid(String domainSid) {
        this.domainSid = domainSid;
        return this;
    }
    
    /**
     * A messaging service SID to associate with a domain. With URL shortening enabled, links in messages sent with the provided messaging service will be shortened to the associated domain
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=MessagingServiceSid")
    public String messagingServiceSid;

    public CreateLinkshorteningMessagingServiceRequest withMessagingServiceSid(String messagingServiceSid) {
        this.messagingServiceSid = messagingServiceSid;
        return this;
    }
    
    public CreateLinkshorteningMessagingServiceRequest(@JsonProperty("DomainSid") String domainSid, @JsonProperty("MessagingServiceSid") String messagingServiceSid) {
        this.domainSid = domainSid;
        this.messagingServiceSid = messagingServiceSid;
  }
}
