/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import circl_dev.twilio_messaging.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CreateUsAppToPersonRequest {
    /**
     * The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/services/api) to create the resources from.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=MessagingServiceSid")
    public String messagingServiceSid;

    public CreateUsAppToPersonRequest withMessagingServiceSid(String messagingServiceSid) {
        this.messagingServiceSid = messagingServiceSid;
        return this;
    }
    
    @SpeakeasyMetadata("request:mediaType=application/x-www-form-urlencoded")
    public CreateUsAppToPersonCreateUsAppToPersonRequest requestBody;

    public CreateUsAppToPersonRequest withRequestBody(CreateUsAppToPersonCreateUsAppToPersonRequest requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    public CreateUsAppToPersonRequest(@JsonProperty("MessagingServiceSid") String messagingServiceSid) {
        this.messagingServiceSid = messagingServiceSid;
  }
}
