/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class CreateExternalCampaignResponse {
    
    public String contentType;

    public CreateExternalCampaignResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public CreateExternalCampaignResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CreateExternalCampaignResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Created
     */
    
    public circl_dev.twilio_messaging.models.shared.MessagingV1ExternalCampaign messagingV1ExternalCampaign;

    public CreateExternalCampaignResponse withMessagingV1ExternalCampaign(circl_dev.twilio_messaging.models.shared.MessagingV1ExternalCampaign messagingV1ExternalCampaign) {
        this.messagingV1ExternalCampaign = messagingV1ExternalCampaign;
        return this;
    }
    
    public CreateExternalCampaignResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
