/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class CreateLinkshorteningMessagingServiceResponse {
    
    public String contentType;

    public CreateLinkshorteningMessagingServiceResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public CreateLinkshorteningMessagingServiceResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CreateLinkshorteningMessagingServiceResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Created
     */
    
    public circl_dev.twilio_messaging.models.shared.MessagingV1LinkshorteningMessagingService messagingV1LinkshorteningMessagingService;

    public CreateLinkshorteningMessagingServiceResponse withMessagingV1LinkshorteningMessagingService(circl_dev.twilio_messaging.models.shared.MessagingV1LinkshorteningMessagingService messagingV1LinkshorteningMessagingService) {
        this.messagingV1LinkshorteningMessagingService = messagingV1LinkshorteningMessagingService;
        return this;
    }
    
    public CreateLinkshorteningMessagingServiceResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
