/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class CreateBrandVettingResponse {
    
    public String contentType;

    public CreateBrandVettingResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public CreateBrandVettingResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CreateBrandVettingResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Created
     */
    
    public circl_dev.twilio_messaging.models.shared.MessagingV1BrandRegistrationsBrandVetting messagingV1BrandRegistrationsBrandVetting;

    public CreateBrandVettingResponse withMessagingV1BrandRegistrationsBrandVetting(circl_dev.twilio_messaging.models.shared.MessagingV1BrandRegistrationsBrandVetting messagingV1BrandRegistrationsBrandVetting) {
        this.messagingV1BrandRegistrationsBrandVetting = messagingV1BrandRegistrationsBrandVetting;
        return this;
    }
    
    public CreateBrandVettingResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
