/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class CreateShortCodeResponse {
    
    public String contentType;

    public CreateShortCodeResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public CreateShortCodeResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CreateShortCodeResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Created
     */
    
    public circl_dev.twilio_messaging.models.shared.MessagingV1ServiceShortCode messagingV1ServiceShortCode;

    public CreateShortCodeResponse withMessagingV1ServiceShortCode(circl_dev.twilio_messaging.models.shared.MessagingV1ServiceShortCode messagingV1ServiceShortCode) {
        this.messagingV1ServiceShortCode = messagingV1ServiceShortCode;
        return this;
    }
    
    public CreateShortCodeResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
