/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class CreateBrandRegistrationOtpResponse {
    
    public String contentType;

    public CreateBrandRegistrationOtpResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public CreateBrandRegistrationOtpResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CreateBrandRegistrationOtpResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Created
     */
    
    public circl_dev.twilio_messaging.models.shared.MessagingV1BrandRegistrationsBrandRegistrationOtp messagingV1BrandRegistrationsBrandRegistrationOtp;

    public CreateBrandRegistrationOtpResponse withMessagingV1BrandRegistrationsBrandRegistrationOtp(circl_dev.twilio_messaging.models.shared.MessagingV1BrandRegistrationsBrandRegistrationOtp messagingV1BrandRegistrationsBrandRegistrationOtp) {
        this.messagingV1BrandRegistrationsBrandRegistrationOtp = messagingV1BrandRegistrationsBrandRegistrationOtp;
        return this;
    }
    
    public CreateBrandRegistrationOtpResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
