/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import circl_dev.twilio_messaging.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CreateBrandVettingRequest {
    /**
     * The SID of the Brand Registration resource of the vettings to create .
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=BrandSid")
    public String brandSid;

    public CreateBrandVettingRequest withBrandSid(String brandSid) {
        this.brandSid = brandSid;
        return this;
    }
    
    @SpeakeasyMetadata("request:mediaType=application/x-www-form-urlencoded")
    public CreateBrandVettingCreateBrandVettingRequest requestBody;

    public CreateBrandVettingRequest withRequestBody(CreateBrandVettingCreateBrandVettingRequest requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    public CreateBrandVettingRequest(@JsonProperty("BrandSid") String brandSid) {
        this.brandSid = brandSid;
  }
}
