/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import circl_dev.twilio_messaging.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CreateExternalCampaignCreateExternalCampaignRequest {
    /**
     * ID of the preregistered campaign.
     */
    @SpeakeasyMetadata("form:name=CampaignId")
    public String campaignId;

    public CreateExternalCampaignCreateExternalCampaignRequest withCampaignId(String campaignId) {
        this.campaignId = campaignId;
        return this;
    }
    
    /**
     * The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/services/api) that the resource is associated with.
     */
    @SpeakeasyMetadata("form:name=MessagingServiceSid")
    public String messagingServiceSid;

    public CreateExternalCampaignCreateExternalCampaignRequest withMessagingServiceSid(String messagingServiceSid) {
        this.messagingServiceSid = messagingServiceSid;
        return this;
    }
    
    public CreateExternalCampaignCreateExternalCampaignRequest(@JsonProperty("CampaignId") String campaignId, @JsonProperty("MessagingServiceSid") String messagingServiceSid) {
        this.campaignId = campaignId;
        this.messagingServiceSid = messagingServiceSid;
  }
}
