/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class CreateTollfreeVerificationResponse {
    
    public String contentType;

    public CreateTollfreeVerificationResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public CreateTollfreeVerificationResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CreateTollfreeVerificationResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Created
     */
    
    public circl_dev.twilio_messaging.models.shared.MessagingV1TollfreeVerification messagingV1TollfreeVerification;

    public CreateTollfreeVerificationResponse withMessagingV1TollfreeVerification(circl_dev.twilio_messaging.models.shared.MessagingV1TollfreeVerification messagingV1TollfreeVerification) {
        this.messagingV1TollfreeVerification = messagingV1TollfreeVerification;
        return this;
    }
    
    public CreateTollfreeVerificationResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
