/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import circl_dev.twilio_messaging.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CreateUsAppToPersonCreateUsAppToPersonRequest {
    /**
     * A2P Brand Registration SID
     */
    @SpeakeasyMetadata("form:name=BrandRegistrationSid")
    public String brandRegistrationSid;

    public CreateUsAppToPersonCreateUsAppToPersonRequest withBrandRegistrationSid(String brandRegistrationSid) {
        this.brandRegistrationSid = brandRegistrationSid;
        return this;
    }
    
    /**
     * A short description of what this SMS campaign does. Min length: 40 characters. Max length: 4096 characters.
     */
    @SpeakeasyMetadata("form:name=Description")
    public String description;

    public CreateUsAppToPersonCreateUsAppToPersonRequest withDescription(String description) {
        this.description = description;
        return this;
    }
    
    /**
     * Indicates that this SMS campaign will send messages that contain links.
     */
    @SpeakeasyMetadata("form:name=HasEmbeddedLinks")
    public Boolean hasEmbeddedLinks;

    public CreateUsAppToPersonCreateUsAppToPersonRequest withHasEmbeddedLinks(Boolean hasEmbeddedLinks) {
        this.hasEmbeddedLinks = hasEmbeddedLinks;
        return this;
    }
    
    /**
     * Indicates that this SMS campaign will send messages that contain phone numbers.
     */
    @SpeakeasyMetadata("form:name=HasEmbeddedPhone")
    public Boolean hasEmbeddedPhone;

    public CreateUsAppToPersonCreateUsAppToPersonRequest withHasEmbeddedPhone(Boolean hasEmbeddedPhone) {
        this.hasEmbeddedPhone = hasEmbeddedPhone;
        return this;
    }
    
    /**
     * End users should be able to text in a keyword to receive help. Those keywords must be provided as part of the campaign registration request. This field is required if managing help keywords yourself (i.e. not using Twilio's Default or Advanced Opt Out features). Values must be alphanumeric. 255 character maximum.
     */
    @SpeakeasyMetadata("form:name=HelpKeywords")
    public String[] helpKeywords;

    public CreateUsAppToPersonCreateUsAppToPersonRequest withHelpKeywords(String[] helpKeywords) {
        this.helpKeywords = helpKeywords;
        return this;
    }
    
    /**
     * When customers receive the help keywords from their end users, Twilio customers are expected to send back an auto-generated response; this may include the brand name and additional support contact information. This field is required if managing help keywords yourself (i.e. not using Twilio's Default or Advanced Opt Out features). 20 character minimum. 320 character maximum.
     */
    @SpeakeasyMetadata("form:name=HelpMessage")
    public String helpMessage;

    public CreateUsAppToPersonCreateUsAppToPersonRequest withHelpMessage(String helpMessage) {
        this.helpMessage = helpMessage;
        return this;
    }
    
    /**
     * Required for all Campaigns. Details around how a consumer opts-in to their campaign, therefore giving consent to receive their messages. If multiple opt-in methods can be used for the same campaign, they must all be listed. 40 character minimum. 2048 character maximum.
     */
    @SpeakeasyMetadata("form:name=MessageFlow")
    public String messageFlow;

    public CreateUsAppToPersonCreateUsAppToPersonRequest withMessageFlow(String messageFlow) {
        this.messageFlow = messageFlow;
        return this;
    }
    
    /**
     * Message samples, at least 1 and up to 5 sample messages (at least 2 for sole proprietor), &gt;=20 chars, &lt;=1024 chars each.
     */
    @SpeakeasyMetadata("form:name=MessageSamples")
    public String[] messageSamples;

    public CreateUsAppToPersonCreateUsAppToPersonRequest withMessageSamples(String[] messageSamples) {
        this.messageSamples = messageSamples;
        return this;
    }
    
    /**
     * If end users can text in a keyword to start receiving messages from this campaign, those keywords must be provided. This field is required if end users can text in a keyword to start receiving messages from this campaign. Values must be alphanumeric. 255 character maximum.
     */
    @SpeakeasyMetadata("form:name=OptInKeywords")
    public String[] optInKeywords;

    public CreateUsAppToPersonCreateUsAppToPersonRequest withOptInKeywords(String[] optInKeywords) {
        this.optInKeywords = optInKeywords;
        return this;
    }
    
    /**
     * If end users can text in a keyword to start receiving messages from this campaign, the auto-reply messages sent to the end users must be provided. The opt-in response should include the Brand name, confirmation of opt-in enrollment to a recurring message campaign, how to get help, and clear description of how to opt-out. This field is required if end users can text in a keyword to start receiving messages from this campaign. 20 character minimum. 320 character maximum.
     */
    @SpeakeasyMetadata("form:name=OptInMessage")
    public String optInMessage;

    public CreateUsAppToPersonCreateUsAppToPersonRequest withOptInMessage(String optInMessage) {
        this.optInMessage = optInMessage;
        return this;
    }
    
    /**
     * End users should be able to text in a keyword to stop receiving messages from this campaign. Those keywords must be provided. This field is required if managing opt out keywords yourself (i.e. not using Twilio's Default or Advanced Opt Out features). Values must be alphanumeric. 255 character maximum.
     */
    @SpeakeasyMetadata("form:name=OptOutKeywords")
    public String[] optOutKeywords;

    public CreateUsAppToPersonCreateUsAppToPersonRequest withOptOutKeywords(String[] optOutKeywords) {
        this.optOutKeywords = optOutKeywords;
        return this;
    }
    
    /**
     * Upon receiving the opt-out keywords from the end users, Twilio customers are expected to send back an auto-generated response, which must provide acknowledgment of the opt-out request and confirmation that no further messages will be sent. It is also recommended that these opt-out messages include the brand name. This field is required if managing opt out keywords yourself (i.e. not using Twilio's Default or Advanced Opt Out features). 20 character minimum. 320 character maximum.
     */
    @SpeakeasyMetadata("form:name=OptOutMessage")
    public String optOutMessage;

    public CreateUsAppToPersonCreateUsAppToPersonRequest withOptOutMessage(String optOutMessage) {
        this.optOutMessage = optOutMessage;
        return this;
    }
    
    /**
     * A2P Campaign Use Case. Examples: [ 2FA, EMERGENCY, MARKETING..]
     */
    @SpeakeasyMetadata("form:name=UsAppToPersonUsecase")
    public String usAppToPersonUsecase;

    public CreateUsAppToPersonCreateUsAppToPersonRequest withUsAppToPersonUsecase(String usAppToPersonUsecase) {
        this.usAppToPersonUsecase = usAppToPersonUsecase;
        return this;
    }
    
    public CreateUsAppToPersonCreateUsAppToPersonRequest(@JsonProperty("BrandRegistrationSid") String brandRegistrationSid, @JsonProperty("Description") String description, @JsonProperty("HasEmbeddedLinks") Boolean hasEmbeddedLinks, @JsonProperty("HasEmbeddedPhone") Boolean hasEmbeddedPhone, @JsonProperty("MessageFlow") String messageFlow, @JsonProperty("MessageSamples") String[] messageSamples, @JsonProperty("UsAppToPersonUsecase") String usAppToPersonUsecase) {
        this.brandRegistrationSid = brandRegistrationSid;
        this.description = description;
        this.hasEmbeddedLinks = hasEmbeddedLinks;
        this.hasEmbeddedPhone = hasEmbeddedPhone;
        this.messageFlow = messageFlow;
        this.messageSamples = messageSamples;
        this.usAppToPersonUsecase = usAppToPersonUsecase;
  }
}
