/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import circl_dev.twilio_messaging.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CreateTollfreeVerificationCreateTollfreeVerificationRequest {
    /**
     * Additional information to be provided for verification.
     */
    @SpeakeasyMetadata("form:name=AdditionalInformation")
    public String additionalInformation;

    public CreateTollfreeVerificationCreateTollfreeVerificationRequest withAdditionalInformation(String additionalInformation) {
        this.additionalInformation = additionalInformation;
        return this;
    }
    
    /**
     * The city of the business or organization using the Tollfree number.
     */
    @SpeakeasyMetadata("form:name=BusinessCity")
    public String businessCity;

    public CreateTollfreeVerificationCreateTollfreeVerificationRequest withBusinessCity(String businessCity) {
        this.businessCity = businessCity;
        return this;
    }
    
    /**
     * The email address of the contact for the business or organization using the Tollfree number.
     */
    @SpeakeasyMetadata("form:name=BusinessContactEmail")
    public String businessContactEmail;

    public CreateTollfreeVerificationCreateTollfreeVerificationRequest withBusinessContactEmail(String businessContactEmail) {
        this.businessContactEmail = businessContactEmail;
        return this;
    }
    
    /**
     * The first name of the contact for the business or organization using the Tollfree number.
     */
    @SpeakeasyMetadata("form:name=BusinessContactFirstName")
    public String businessContactFirstName;

    public CreateTollfreeVerificationCreateTollfreeVerificationRequest withBusinessContactFirstName(String businessContactFirstName) {
        this.businessContactFirstName = businessContactFirstName;
        return this;
    }
    
    /**
     * The last name of the contact for the business or organization using the Tollfree number.
     */
    @SpeakeasyMetadata("form:name=BusinessContactLastName")
    public String businessContactLastName;

    public CreateTollfreeVerificationCreateTollfreeVerificationRequest withBusinessContactLastName(String businessContactLastName) {
        this.businessContactLastName = businessContactLastName;
        return this;
    }
    
    /**
     * The phone number of the contact for the business or organization using the Tollfree number.
     */
    @SpeakeasyMetadata("form:name=BusinessContactPhone")
    public String businessContactPhone;

    public CreateTollfreeVerificationCreateTollfreeVerificationRequest withBusinessContactPhone(String businessContactPhone) {
        this.businessContactPhone = businessContactPhone;
        return this;
    }
    
    /**
     * The country of the business or organization using the Tollfree number.
     */
    @SpeakeasyMetadata("form:name=BusinessCountry")
    public String businessCountry;

    public CreateTollfreeVerificationCreateTollfreeVerificationRequest withBusinessCountry(String businessCountry) {
        this.businessCountry = businessCountry;
        return this;
    }
    
    /**
     * The name of the business or organization using the Tollfree number.
     */
    @SpeakeasyMetadata("form:name=BusinessName")
    public String businessName;

    public CreateTollfreeVerificationCreateTollfreeVerificationRequest withBusinessName(String businessName) {
        this.businessName = businessName;
        return this;
    }
    
    /**
     * The postal code of the business or organization using the Tollfree number.
     */
    @SpeakeasyMetadata("form:name=BusinessPostalCode")
    public String businessPostalCode;

    public CreateTollfreeVerificationCreateTollfreeVerificationRequest withBusinessPostalCode(String businessPostalCode) {
        this.businessPostalCode = businessPostalCode;
        return this;
    }
    
    /**
     * The state/province/region of the business or organization using the Tollfree number.
     */
    @SpeakeasyMetadata("form:name=BusinessStateProvinceRegion")
    public String businessStateProvinceRegion;

    public CreateTollfreeVerificationCreateTollfreeVerificationRequest withBusinessStateProvinceRegion(String businessStateProvinceRegion) {
        this.businessStateProvinceRegion = businessStateProvinceRegion;
        return this;
    }
    
    /**
     * The address of the business or organization using the Tollfree number.
     */
    @SpeakeasyMetadata("form:name=BusinessStreetAddress")
    public String businessStreetAddress;

    public CreateTollfreeVerificationCreateTollfreeVerificationRequest withBusinessStreetAddress(String businessStreetAddress) {
        this.businessStreetAddress = businessStreetAddress;
        return this;
    }
    
    /**
     * The address of the business or organization using the Tollfree number.
     */
    @SpeakeasyMetadata("form:name=BusinessStreetAddress2")
    public String businessStreetAddress2;

    public CreateTollfreeVerificationCreateTollfreeVerificationRequest withBusinessStreetAddress2(String businessStreetAddress2) {
        this.businessStreetAddress2 = businessStreetAddress2;
        return this;
    }
    
    /**
     * The website of the business or organization using the Tollfree number.
     */
    @SpeakeasyMetadata("form:name=BusinessWebsite")
    public String businessWebsite;

    public CreateTollfreeVerificationCreateTollfreeVerificationRequest withBusinessWebsite(String businessWebsite) {
        this.businessWebsite = businessWebsite;
        return this;
    }
    
    /**
     * Customer's Profile Bundle BundleSid.
     */
    @SpeakeasyMetadata("form:name=CustomerProfileSid")
    public String customerProfileSid;

    public CreateTollfreeVerificationCreateTollfreeVerificationRequest withCustomerProfileSid(String customerProfileSid) {
        this.customerProfileSid = customerProfileSid;
        return this;
    }
    
    /**
     * An optional external reference ID supplied by customer and echoed back on status retrieval.
     */
    @SpeakeasyMetadata("form:name=ExternalReferenceId")
    public String externalReferenceId;

    public CreateTollfreeVerificationCreateTollfreeVerificationRequest withExternalReferenceId(String externalReferenceId) {
        this.externalReferenceId = externalReferenceId;
        return this;
    }
    
    /**
     * Estimate monthly volume of messages from the Tollfree Number.
     */
    @SpeakeasyMetadata("form:name=MessageVolume")
    public String messageVolume;

    public CreateTollfreeVerificationCreateTollfreeVerificationRequest withMessageVolume(String messageVolume) {
        this.messageVolume = messageVolume;
        return this;
    }
    
    /**
     * The email address to receive the notification about the verification result. .
     */
    @SpeakeasyMetadata("form:name=NotificationEmail")
    public String notificationEmail;

    public CreateTollfreeVerificationCreateTollfreeVerificationRequest withNotificationEmail(String notificationEmail) {
        this.notificationEmail = notificationEmail;
        return this;
    }
    
    /**
     * Link to an image that shows the opt-in workflow. Multiple images allowed and must be a publicly hosted URL.
     */
    @SpeakeasyMetadata("form:name=OptInImageUrls")
    public String[] optInImageUrls;

    public CreateTollfreeVerificationCreateTollfreeVerificationRequest withOptInImageUrls(String[] optInImageUrls) {
        this.optInImageUrls = optInImageUrls;
        return this;
    }
    
    @SpeakeasyMetadata("form:name=OptInType")
    public circl_dev.twilio_messaging.models.shared.TollfreeVerificationEnumOptInType optInType;

    public CreateTollfreeVerificationCreateTollfreeVerificationRequest withOptInType(circl_dev.twilio_messaging.models.shared.TollfreeVerificationEnumOptInType optInType) {
        this.optInType = optInType;
        return this;
    }
    
    /**
     * An example of message content, i.e. a sample message.
     */
    @SpeakeasyMetadata("form:name=ProductionMessageSample")
    public String productionMessageSample;

    public CreateTollfreeVerificationCreateTollfreeVerificationRequest withProductionMessageSample(String productionMessageSample) {
        this.productionMessageSample = productionMessageSample;
        return this;
    }
    
    /**
     * The SID of the Phone Number associated with the Tollfree Verification.
     */
    @SpeakeasyMetadata("form:name=TollfreePhoneNumberSid")
    public String tollfreePhoneNumberSid;

    public CreateTollfreeVerificationCreateTollfreeVerificationRequest withTollfreePhoneNumberSid(String tollfreePhoneNumberSid) {
        this.tollfreePhoneNumberSid = tollfreePhoneNumberSid;
        return this;
    }
    
    /**
     * The category of the use case for the Tollfree Number. List as many are applicable..
     */
    @SpeakeasyMetadata("form:name=UseCaseCategories")
    public String[] useCaseCategories;

    public CreateTollfreeVerificationCreateTollfreeVerificationRequest withUseCaseCategories(String[] useCaseCategories) {
        this.useCaseCategories = useCaseCategories;
        return this;
    }
    
    /**
     * Use this to further explain how messaging is used by the business or organization.
     */
    @SpeakeasyMetadata("form:name=UseCaseSummary")
    public String useCaseSummary;

    public CreateTollfreeVerificationCreateTollfreeVerificationRequest withUseCaseSummary(String useCaseSummary) {
        this.useCaseSummary = useCaseSummary;
        return this;
    }
    
    public CreateTollfreeVerificationCreateTollfreeVerificationRequest(@JsonProperty("BusinessName") String businessName, @JsonProperty("BusinessWebsite") String businessWebsite, @JsonProperty("MessageVolume") String messageVolume, @JsonProperty("NotificationEmail") String notificationEmail, @JsonProperty("OptInImageUrls") String[] optInImageUrls, @JsonProperty("OptInType") circl_dev.twilio_messaging.models.shared.TollfreeVerificationEnumOptInType optInType, @JsonProperty("ProductionMessageSample") String productionMessageSample, @JsonProperty("TollfreePhoneNumberSid") String tollfreePhoneNumberSid, @JsonProperty("UseCaseCategories") String[] useCaseCategories, @JsonProperty("UseCaseSummary") String useCaseSummary) {
        this.businessName = businessName;
        this.businessWebsite = businessWebsite;
        this.messageVolume = messageVolume;
        this.notificationEmail = notificationEmail;
        this.optInImageUrls = optInImageUrls;
        this.optInType = optInType;
        this.productionMessageSample = productionMessageSample;
        this.tollfreePhoneNumberSid = tollfreePhoneNumberSid;
        this.useCaseCategories = useCaseCategories;
        this.useCaseSummary = useCaseSummary;
  }
}
