/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import circl_dev.twilio_messaging.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class DeleteUsAppToPersonRequest {
    /**
     * The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/services/api) to delete the resource from.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=MessagingServiceSid")
    public String messagingServiceSid;

    public DeleteUsAppToPersonRequest withMessagingServiceSid(String messagingServiceSid) {
        this.messagingServiceSid = messagingServiceSid;
        return this;
    }
    
    /**
     * The SID of the US A2P Compliance resource to delete `QE2c6890da8086d771620e9b13fadeba0b`.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=Sid")
    public String sid;

    public DeleteUsAppToPersonRequest withSid(String sid) {
        this.sid = sid;
        return this;
    }
    
    public DeleteUsAppToPersonRequest(@JsonProperty("MessagingServiceSid") String messagingServiceSid, @JsonProperty("Sid") String sid) {
        this.messagingServiceSid = messagingServiceSid;
        this.sid = sid;
  }
}
