/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import circl_dev.twilio_messaging.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class FetchBrandVettingRequest {
    /**
     * The SID of the Brand Registration resource of the vettings to read .
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=BrandSid")
    public String brandSid;

    public FetchBrandVettingRequest withBrandSid(String brandSid) {
        this.brandSid = brandSid;
        return this;
    }
    
    /**
     * The Twilio SID of the third-party vetting record.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=BrandVettingSid")
    public String brandVettingSid;

    public FetchBrandVettingRequest withBrandVettingSid(String brandVettingSid) {
        this.brandVettingSid = brandVettingSid;
        return this;
    }
    
    public FetchBrandVettingRequest(@JsonProperty("BrandSid") String brandSid, @JsonProperty("BrandVettingSid") String brandVettingSid) {
        this.brandSid = brandSid;
        this.brandVettingSid = brandVettingSid;
  }
}
