/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import circl_dev.twilio_messaging.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class FetchLinkshorteningMessagingServiceDomainAssociationRequest {
    /**
     * Unique string used to identify the Messaging service that this domain should be associated with.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=MessagingServiceSid")
    public String messagingServiceSid;

    public FetchLinkshorteningMessagingServiceDomainAssociationRequest withMessagingServiceSid(String messagingServiceSid) {
        this.messagingServiceSid = messagingServiceSid;
        return this;
    }
    
    public FetchLinkshorteningMessagingServiceDomainAssociationRequest(@JsonProperty("MessagingServiceSid") String messagingServiceSid) {
        this.messagingServiceSid = messagingServiceSid;
  }
}
