/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import circl_dev.twilio_messaging.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class FetchDomainConfigRequest {
    /**
     * Unique string used to identify the domain that this config should be associated with.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=DomainSid")
    public String domainSid;

    public FetchDomainConfigRequest withDomainSid(String domainSid) {
        this.domainSid = domainSid;
        return this;
    }
    
    public FetchDomainConfigRequest(@JsonProperty("DomainSid") String domainSid) {
        this.domainSid = domainSid;
  }
}
