/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import circl_dev.twilio_messaging.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class FetchUsAppToPersonUsecaseRequest {
    /**
     * The unique string to identify the A2P brand.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=BrandRegistrationSid")
    public String brandRegistrationSid;

    public FetchUsAppToPersonUsecaseRequest withBrandRegistrationSid(String brandRegistrationSid) {
        this.brandRegistrationSid = brandRegistrationSid;
        return this;
    }
    
    /**
     * The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/services/api) to fetch the resource from.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=MessagingServiceSid")
    public String messagingServiceSid;

    public FetchUsAppToPersonUsecaseRequest withMessagingServiceSid(String messagingServiceSid) {
        this.messagingServiceSid = messagingServiceSid;
        return this;
    }
    
    public FetchUsAppToPersonUsecaseRequest(@JsonProperty("MessagingServiceSid") String messagingServiceSid) {
        this.messagingServiceSid = messagingServiceSid;
  }
}
