/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class FetchUsAppToPersonUsecaseResponse {
    
    public String contentType;

    public FetchUsAppToPersonUsecaseResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public FetchUsAppToPersonUsecaseResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public FetchUsAppToPersonUsecaseResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public circl_dev.twilio_messaging.models.shared.MessagingV1ServiceUsAppToPersonUsecase messagingV1ServiceUsAppToPersonUsecase;

    public FetchUsAppToPersonUsecaseResponse withMessagingV1ServiceUsAppToPersonUsecase(circl_dev.twilio_messaging.models.shared.MessagingV1ServiceUsAppToPersonUsecase messagingV1ServiceUsAppToPersonUsecase) {
        this.messagingV1ServiceUsAppToPersonUsecase = messagingV1ServiceUsAppToPersonUsecase;
        return this;
    }
    
    public FetchUsAppToPersonUsecaseResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
