/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class FetchDeactivationResponse {
    
    public String contentType;

    public FetchDeactivationResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public FetchDeactivationResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public FetchDeactivationResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Temporary Redirect
     */
    
    public circl_dev.twilio_messaging.models.shared.MessagingV1Deactivation messagingV1Deactivation;

    public FetchDeactivationResponse withMessagingV1Deactivation(circl_dev.twilio_messaging.models.shared.MessagingV1Deactivation messagingV1Deactivation) {
        this.messagingV1Deactivation = messagingV1Deactivation;
        return this;
    }
    
    public FetchDeactivationResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
