/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class FetchDomainConfigMessagingServiceResponse {
    
    public String contentType;

    public FetchDomainConfigMessagingServiceResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public FetchDomainConfigMessagingServiceResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public FetchDomainConfigMessagingServiceResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public circl_dev.twilio_messaging.models.shared.MessagingV1DomainConfigMessagingService messagingV1DomainConfigMessagingService;

    public FetchDomainConfigMessagingServiceResponse withMessagingV1DomainConfigMessagingService(circl_dev.twilio_messaging.models.shared.MessagingV1DomainConfigMessagingService messagingV1DomainConfigMessagingService) {
        this.messagingV1DomainConfigMessagingService = messagingV1DomainConfigMessagingService;
        return this;
    }
    
    public FetchDomainConfigMessagingServiceResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
