/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class FetchLinkshorteningMessagingServiceDomainAssociationResponse {
    
    public String contentType;

    public FetchLinkshorteningMessagingServiceDomainAssociationResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public FetchLinkshorteningMessagingServiceDomainAssociationResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public FetchLinkshorteningMessagingServiceDomainAssociationResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public circl_dev.twilio_messaging.models.shared.MessagingV1LinkshorteningMessagingServiceDomainAssociation messagingV1LinkshorteningMessagingServiceDomainAssociation;

    public FetchLinkshorteningMessagingServiceDomainAssociationResponse withMessagingV1LinkshorteningMessagingServiceDomainAssociation(circl_dev.twilio_messaging.models.shared.MessagingV1LinkshorteningMessagingServiceDomainAssociation messagingV1LinkshorteningMessagingServiceDomainAssociation) {
        this.messagingV1LinkshorteningMessagingServiceDomainAssociation = messagingV1LinkshorteningMessagingServiceDomainAssociation;
        return this;
    }
    
    public FetchLinkshorteningMessagingServiceDomainAssociationResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
