/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import circl_dev.twilio_messaging.utils.SpeakeasyMetadata;
import java.time.LocalDate;


public class FetchDeactivationRequest {
    /**
     * The request will return a list of all United States Phone Numbers that were deactivated on the day specified by this parameter. This date should be specified in YYYY-MM-DD format.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=Date")
    public LocalDate date;

    public FetchDeactivationRequest withDate(LocalDate date) {
        this.date = date;
        return this;
    }
    
    public FetchDeactivationRequest(){}
}
