/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class FetchUsecaseResponse {
    
    public String contentType;

    public FetchUsecaseResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public FetchUsecaseResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public FetchUsecaseResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public circl_dev.twilio_messaging.models.shared.MessagingV1Usecase messagingV1Usecase;

    public FetchUsecaseResponse withMessagingV1Usecase(circl_dev.twilio_messaging.models.shared.MessagingV1Usecase messagingV1Usecase) {
        this.messagingV1Usecase = messagingV1Usecase;
        return this;
    }
    
    public FetchUsecaseResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
