/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ListTollfreeVerificationListTollfreeVerificationResponse - OK
 */

public class ListTollfreeVerificationListTollfreeVerificationResponse {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("meta")
    public ListTollfreeVerificationListTollfreeVerificationResponseMeta meta;

    public ListTollfreeVerificationListTollfreeVerificationResponse withMeta(ListTollfreeVerificationListTollfreeVerificationResponseMeta meta) {
        this.meta = meta;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("verifications")
    public circl_dev.twilio_messaging.models.shared.MessagingV1TollfreeVerification[] verifications;

    public ListTollfreeVerificationListTollfreeVerificationResponse withVerifications(circl_dev.twilio_messaging.models.shared.MessagingV1TollfreeVerification[] verifications) {
        this.verifications = verifications;
        return this;
    }
    
    public ListTollfreeVerificationListTollfreeVerificationResponse(){}
}
