/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ListBrandRegistrationsListBrandRegistrationsResponse - OK
 */

public class ListBrandRegistrationsListBrandRegistrationsResponse {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public circl_dev.twilio_messaging.models.shared.MessagingV1BrandRegistrations[] data;

    public ListBrandRegistrationsListBrandRegistrationsResponse withData(circl_dev.twilio_messaging.models.shared.MessagingV1BrandRegistrations[] data) {
        this.data = data;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("meta")
    public ListBrandRegistrationsListBrandRegistrationsResponseMeta meta;

    public ListBrandRegistrationsListBrandRegistrationsResponse withMeta(ListBrandRegistrationsListBrandRegistrationsResponseMeta meta) {
        this.meta = meta;
        return this;
    }
    
    public ListBrandRegistrationsListBrandRegistrationsResponse(){}
}
