/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ListAlphaSenderListAlphaSenderResponse - OK
 */

public class ListAlphaSenderListAlphaSenderResponse {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("alpha_senders")
    public circl_dev.twilio_messaging.models.shared.MessagingV1ServiceAlphaSender[] alphaSenders;

    public ListAlphaSenderListAlphaSenderResponse withAlphaSenders(circl_dev.twilio_messaging.models.shared.MessagingV1ServiceAlphaSender[] alphaSenders) {
        this.alphaSenders = alphaSenders;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("meta")
    public ListAlphaSenderListAlphaSenderResponseMeta meta;

    public ListAlphaSenderListAlphaSenderResponse withMeta(ListAlphaSenderListAlphaSenderResponseMeta meta) {
        this.meta = meta;
        return this;
    }
    
    public ListAlphaSenderListAlphaSenderResponse(){}
}
