/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import circl_dev.twilio_messaging.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class ListBrandVettingRequest {
    /**
     * The SID of the Brand Registration resource of the vettings to read .
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=BrandSid")
    public String brandSid;

    public ListBrandVettingRequest withBrandSid(String brandSid) {
        this.brandSid = brandSid;
        return this;
    }
    
    /**
     * The page index. This value is simply for client state.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=Page")
    public Long page;

    public ListBrandVettingRequest withPage(Long page) {
        this.page = page;
        return this;
    }
    
    /**
     * How many resources to return in each list page. The default is 50, and the maximum is 1000.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=PageSize")
    public Long pageSize;

    public ListBrandVettingRequest withPageSize(Long pageSize) {
        this.pageSize = pageSize;
        return this;
    }
    
    /**
     * The page token. This is provided by the API.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=PageToken")
    public String pageToken;

    public ListBrandVettingRequest withPageToken(String pageToken) {
        this.pageToken = pageToken;
        return this;
    }
    
    /**
     * The third-party provider of the vettings to read
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=VettingProvider")
    public circl_dev.twilio_messaging.models.shared.BrandVettingEnumVettingProvider vettingProvider;

    public ListBrandVettingRequest withVettingProvider(circl_dev.twilio_messaging.models.shared.BrandVettingEnumVettingProvider vettingProvider) {
        this.vettingProvider = vettingProvider;
        return this;
    }
    
    public ListBrandVettingRequest(@JsonProperty("BrandSid") String brandSid) {
        this.brandSid = brandSid;
  }
}
