/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class ListBrandRegistrationsResponse {
    
    public String contentType;

    public ListBrandRegistrationsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * OK
     */
    
    public ListBrandRegistrationsListBrandRegistrationsResponse listBrandRegistrationsResponse;

    public ListBrandRegistrationsResponse withListBrandRegistrationsResponse(ListBrandRegistrationsListBrandRegistrationsResponse listBrandRegistrationsResponse) {
        this.listBrandRegistrationsResponse = listBrandRegistrationsResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public ListBrandRegistrationsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListBrandRegistrationsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ListBrandRegistrationsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
