/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class ListShortCodeResponse {
    
    public String contentType;

    public ListShortCodeResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * OK
     */
    
    public ListShortCodeListShortCodeResponse listShortCodeResponse;

    public ListShortCodeResponse withListShortCodeResponse(ListShortCodeListShortCodeResponse listShortCodeResponse) {
        this.listShortCodeResponse = listShortCodeResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public ListShortCodeResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListShortCodeResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ListShortCodeResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
