/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class ListTollfreeVerificationResponse {
    
    public String contentType;

    public ListTollfreeVerificationResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * OK
     */
    
    public ListTollfreeVerificationListTollfreeVerificationResponse listTollfreeVerificationResponse;

    public ListTollfreeVerificationResponse withListTollfreeVerificationResponse(ListTollfreeVerificationListTollfreeVerificationResponse listTollfreeVerificationResponse) {
        this.listTollfreeVerificationResponse = listTollfreeVerificationResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public ListTollfreeVerificationResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListTollfreeVerificationResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ListTollfreeVerificationResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
