/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ListShortCodeListShortCodeResponse - OK
 */

public class ListShortCodeListShortCodeResponse {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("meta")
    public ListShortCodeListShortCodeResponseMeta meta;

    public ListShortCodeListShortCodeResponse withMeta(ListShortCodeListShortCodeResponseMeta meta) {
        this.meta = meta;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("short_codes")
    public circl_dev.twilio_messaging.models.shared.MessagingV1ServiceShortCode[] shortCodes;

    public ListShortCodeListShortCodeResponse withShortCodes(circl_dev.twilio_messaging.models.shared.MessagingV1ServiceShortCode[] shortCodes) {
        this.shortCodes = shortCodes;
        return this;
    }
    
    public ListShortCodeListShortCodeResponse(){}
}
