/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ListUsAppToPersonListUsAppToPersonResponse - OK
 */

public class ListUsAppToPersonListUsAppToPersonResponse {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("compliance")
    public circl_dev.twilio_messaging.models.shared.MessagingV1ServiceUsAppToPerson[] compliance;

    public ListUsAppToPersonListUsAppToPersonResponse withCompliance(circl_dev.twilio_messaging.models.shared.MessagingV1ServiceUsAppToPerson[] compliance) {
        this.compliance = compliance;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("meta")
    public ListUsAppToPersonListUsAppToPersonResponseMeta meta;

    public ListUsAppToPersonListUsAppToPersonResponse withMeta(ListUsAppToPersonListUsAppToPersonResponseMeta meta) {
        this.meta = meta;
        return this;
    }
    
    public ListUsAppToPersonListUsAppToPersonResponse(){}
}
