/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class ListAlphaSenderResponse {
    
    public String contentType;

    public ListAlphaSenderResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * OK
     */
    
    public ListAlphaSenderListAlphaSenderResponse listAlphaSenderResponse;

    public ListAlphaSenderResponse withListAlphaSenderResponse(ListAlphaSenderListAlphaSenderResponse listAlphaSenderResponse) {
        this.listAlphaSenderResponse = listAlphaSenderResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public ListAlphaSenderResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListAlphaSenderResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ListAlphaSenderResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
