/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import circl_dev.twilio_messaging.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class UpdateDomainCertV4UpdateDomainCertV4Request {
    /**
     * Contains the full TLS certificate and private for this domain in PEM format: https://en.wikipedia.org/wiki/Privacy-Enhanced_Mail. Twilio uses this information to process HTTPS traffic sent to your domain.
     */
    @SpeakeasyMetadata("form:name=TlsCert")
    public String tlsCert;

    public UpdateDomainCertV4UpdateDomainCertV4Request withTlsCert(String tlsCert) {
        this.tlsCert = tlsCert;
        return this;
    }
    
    public UpdateDomainCertV4UpdateDomainCertV4Request(@JsonProperty("TlsCert") String tlsCert) {
        this.tlsCert = tlsCert;
  }
}
