/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class UpdateBrandRegistrationsResponse {
    
    public String contentType;

    public UpdateBrandRegistrationsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public UpdateBrandRegistrationsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public UpdateBrandRegistrationsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Accepted
     */
    
    public circl_dev.twilio_messaging.models.shared.MessagingV1BrandRegistrations messagingV1BrandRegistrations;

    public UpdateBrandRegistrationsResponse withMessagingV1BrandRegistrations(circl_dev.twilio_messaging.models.shared.MessagingV1BrandRegistrations messagingV1BrandRegistrations) {
        this.messagingV1BrandRegistrations = messagingV1BrandRegistrations;
        return this;
    }
    
    public UpdateBrandRegistrationsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
