/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import circl_dev.twilio_messaging.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class UpdateServiceRequest {
    @SpeakeasyMetadata("request:mediaType=application/x-www-form-urlencoded")
    public UpdateServiceUpdateServiceRequest1 requestBody;

    public UpdateServiceRequest withRequestBody(UpdateServiceUpdateServiceRequest1 requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * The SID of the Service resource to update.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=Sid")
    public String sid;

    public UpdateServiceRequest withSid(String sid) {
        this.sid = sid;
        return this;
    }
    
    public UpdateServiceRequest(@JsonProperty("Sid") String sid) {
        this.sid = sid;
  }
}
