/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class UpdateDomainConfigResponse {
    
    public String contentType;

    public UpdateDomainConfigResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public UpdateDomainConfigResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public UpdateDomainConfigResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public circl_dev.twilio_messaging.models.shared.MessagingV1DomainConfig messagingV1DomainConfig;

    public UpdateDomainConfigResponse withMessagingV1DomainConfig(circl_dev.twilio_messaging.models.shared.MessagingV1DomainConfig messagingV1DomainConfig) {
        this.messagingV1DomainConfig = messagingV1DomainConfig;
        return this;
    }
    
    public UpdateDomainConfigResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
