/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import circl_dev.twilio_messaging.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class UpdateDomainCertV4Request {
    /**
     * Unique string used to identify the domain that this certificate should be associated with.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=DomainSid")
    public String domainSid;

    public UpdateDomainCertV4Request withDomainSid(String domainSid) {
        this.domainSid = domainSid;
        return this;
    }
    
    @SpeakeasyMetadata("request:mediaType=application/x-www-form-urlencoded")
    public UpdateDomainCertV4UpdateDomainCertV4Request requestBody;

    public UpdateDomainCertV4Request withRequestBody(UpdateDomainCertV4UpdateDomainCertV4Request requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    public UpdateDomainCertV4Request(@JsonProperty("DomainSid") String domainSid) {
        this.domainSid = domainSid;
  }
}
