/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class UpdateDomainCertV4Response {
    
    public String contentType;

    public UpdateDomainCertV4Response withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public UpdateDomainCertV4Response withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public UpdateDomainCertV4Response withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public circl_dev.twilio_messaging.models.shared.MessagingV1DomainCertV4 messagingV1DomainCertV4;

    public UpdateDomainCertV4Response withMessagingV1DomainCertV4(circl_dev.twilio_messaging.models.shared.MessagingV1DomainCertV4 messagingV1DomainCertV4) {
        this.messagingV1DomainCertV4 = messagingV1DomainCertV4;
        return this;
    }
    
    public UpdateDomainCertV4Response(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
