/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging.models.operations;

import circl_dev.twilio_messaging.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class UpdateDomainConfigRequest {
    /**
     * Unique string used to identify the domain that this config should be associated with.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=DomainSid")
    public String domainSid;

    public UpdateDomainConfigRequest withDomainSid(String domainSid) {
        this.domainSid = domainSid;
        return this;
    }
    
    @SpeakeasyMetadata("request:mediaType=application/x-www-form-urlencoded")
    public UpdateDomainConfigUpdateDomainConfigRequest requestBody;

    public UpdateDomainConfigRequest withRequestBody(UpdateDomainConfigUpdateDomainConfigRequest requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    public UpdateDomainConfigRequest(@JsonProperty("DomainSid") String domainSid) {
        this.domainSid = domainSid;
  }
}
