/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging;

import circl_dev.twilio_messaging.utils.HTTPClient;
import circl_dev.twilio_messaging.utils.HTTPRequest;
import circl_dev.twilio_messaging.utils.JSON;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;

public class MessagingV1LinkshorteningMessagingService {
	
    /**
	 * CREATE_LINKSHORTENING_MESSAGING_SERVICE_SERVERS contains the list of server urls available to the SDK.
	 */
    public static final String[] CREATE_LINKSHORTENING_MESSAGING_SERVICE_SERVERS = {
        "https://messaging.twilio.com",
    };
	
    /**
	 * DELETE_LINKSHORTENING_MESSAGING_SERVICE_SERVERS contains the list of server urls available to the SDK.
	 */
    public static final String[] DELETE_LINKSHORTENING_MESSAGING_SERVICE_SERVERS = {
        "https://messaging.twilio.com",
    };
	
	private SDKConfiguration sdkConfiguration;

	public MessagingV1LinkshorteningMessagingService(SDKConfiguration sdkConfiguration) {
		this.sdkConfiguration = sdkConfiguration;
	}

    public circl_dev.twilio_messaging.models.operations.CreateLinkshorteningMessagingServiceResponse createLinkshorteningMessagingService(circl_dev.twilio_messaging.models.operations.CreateLinkshorteningMessagingServiceRequest request, circl_dev.twilio_messaging.models.operations.CreateLinkshorteningMessagingServiceSecurity security) throws Exception {
        return this.createLinkshorteningMessagingService(request, security, null);
    }

    public circl_dev.twilio_messaging.models.operations.CreateLinkshorteningMessagingServiceResponse createLinkshorteningMessagingService(circl_dev.twilio_messaging.models.operations.CreateLinkshorteningMessagingServiceRequest request, circl_dev.twilio_messaging.models.operations.CreateLinkshorteningMessagingServiceSecurity security, String serverURL) throws Exception {
        String baseUrl = circl_dev.twilio_messaging.utils.Utils.templateUrl(CREATE_LINKSHORTENING_MESSAGING_SERVICE_SERVERS[0], new java.util.HashMap<String, String>());
        if (serverURL != null && !serverURL.isBlank()) {
            baseUrl = serverURL;
        }
        
        String url = circl_dev.twilio_messaging.utils.Utils.generateURL(circl_dev.twilio_messaging.models.operations.CreateLinkshorteningMessagingServiceRequest.class, baseUrl, "/v1/LinkShortening/Domains/{DomainSid}/MessagingServices/{MessagingServiceSid}", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        
        HTTPClient client = circl_dev.twilio_messaging.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        circl_dev.twilio_messaging.models.operations.CreateLinkshorteningMessagingServiceResponse res = new circl_dev.twilio_messaging.models.operations.CreateLinkshorteningMessagingServiceResponse(contentType, httpRes.statusCode()) {{
            messagingV1LinkshorteningMessagingService = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 201) {
            if (circl_dev.twilio_messaging.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                circl_dev.twilio_messaging.models.shared.MessagingV1LinkshorteningMessagingService out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), circl_dev.twilio_messaging.models.shared.MessagingV1LinkshorteningMessagingService.class);
                res.messagingV1LinkshorteningMessagingService = out;
            }
        }

        return res;
    }

    public circl_dev.twilio_messaging.models.operations.DeleteLinkshorteningMessagingServiceResponse deleteLinkshorteningMessagingService(circl_dev.twilio_messaging.models.operations.DeleteLinkshorteningMessagingServiceRequest request, circl_dev.twilio_messaging.models.operations.DeleteLinkshorteningMessagingServiceSecurity security) throws Exception {
        return this.deleteLinkshorteningMessagingService(request, security, null);
    }

    public circl_dev.twilio_messaging.models.operations.DeleteLinkshorteningMessagingServiceResponse deleteLinkshorteningMessagingService(circl_dev.twilio_messaging.models.operations.DeleteLinkshorteningMessagingServiceRequest request, circl_dev.twilio_messaging.models.operations.DeleteLinkshorteningMessagingServiceSecurity security, String serverURL) throws Exception {
        String baseUrl = circl_dev.twilio_messaging.utils.Utils.templateUrl(DELETE_LINKSHORTENING_MESSAGING_SERVICE_SERVERS[0], new java.util.HashMap<String, String>());
        if (serverURL != null && !serverURL.isBlank()) {
            baseUrl = serverURL;
        }
        
        String url = circl_dev.twilio_messaging.utils.Utils.generateURL(circl_dev.twilio_messaging.models.operations.DeleteLinkshorteningMessagingServiceRequest.class, baseUrl, "/v1/LinkShortening/Domains/{DomainSid}/MessagingServices/{MessagingServiceSid}", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("DELETE");
        req.setURL(url);

        req.addHeader("Accept", "*/*");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        
        HTTPClient client = circl_dev.twilio_messaging.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        circl_dev.twilio_messaging.models.operations.DeleteLinkshorteningMessagingServiceResponse res = new circl_dev.twilio_messaging.models.operations.DeleteLinkshorteningMessagingServiceResponse(contentType, httpRes.statusCode()) {{
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 204) {
        }

        return res;
    }
}