/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging;

import circl_dev.twilio_messaging.utils.HTTPClient;
import circl_dev.twilio_messaging.utils.HTTPRequest;
import circl_dev.twilio_messaging.utils.JSON;
import circl_dev.twilio_messaging.utils.SerializedBody;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.OffsetDateTime;
import org.apache.http.NameValuePair;

public class MessagingV1ShortCode {
	
    /**
	 * CREATE_SHORT_CODE_SERVERS contains the list of server urls available to the SDK.
	 */
    public static final String[] CREATE_SHORT_CODE_SERVERS = {
        "https://messaging.twilio.com",
    };
	
    /**
	 * DELETE_SHORT_CODE_SERVERS contains the list of server urls available to the SDK.
	 */
    public static final String[] DELETE_SHORT_CODE_SERVERS = {
        "https://messaging.twilio.com",
    };
	
    /**
	 * FETCH_SHORT_CODE_SERVERS contains the list of server urls available to the SDK.
	 */
    public static final String[] FETCH_SHORT_CODE_SERVERS = {
        "https://messaging.twilio.com",
    };
	
    /**
	 * LIST_SHORT_CODE_SERVERS contains the list of server urls available to the SDK.
	 */
    public static final String[] LIST_SHORT_CODE_SERVERS = {
        "https://messaging.twilio.com",
    };
	
	private SDKConfiguration sdkConfiguration;

	public MessagingV1ShortCode(SDKConfiguration sdkConfiguration) {
		this.sdkConfiguration = sdkConfiguration;
	}

    public circl_dev.twilio_messaging.models.operations.CreateShortCodeResponse createShortCode(circl_dev.twilio_messaging.models.operations.CreateShortCodeRequest request, circl_dev.twilio_messaging.models.operations.CreateShortCodeSecurity security) throws Exception {
        return this.createShortCode(request, security, null);
    }

    public circl_dev.twilio_messaging.models.operations.CreateShortCodeResponse createShortCode(circl_dev.twilio_messaging.models.operations.CreateShortCodeRequest request, circl_dev.twilio_messaging.models.operations.CreateShortCodeSecurity security, String serverURL) throws Exception {
        String baseUrl = circl_dev.twilio_messaging.utils.Utils.templateUrl(CREATE_SHORT_CODE_SERVERS[0], new java.util.HashMap<String, String>());
        if (serverURL != null && !serverURL.isBlank()) {
            baseUrl = serverURL;
        }
        
        String url = circl_dev.twilio_messaging.utils.Utils.generateURL(circl_dev.twilio_messaging.models.operations.CreateShortCodeRequest.class, baseUrl, "/v1/Services/{ServiceSid}/ShortCodes", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        SerializedBody serializedRequestBody = circl_dev.twilio_messaging.utils.Utils.serializeRequestBody(request, "requestBody", "form");
        req.setBody(serializedRequestBody);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        
        HTTPClient client = circl_dev.twilio_messaging.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        circl_dev.twilio_messaging.models.operations.CreateShortCodeResponse res = new circl_dev.twilio_messaging.models.operations.CreateShortCodeResponse(contentType, httpRes.statusCode()) {{
            messagingV1ServiceShortCode = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 201) {
            if (circl_dev.twilio_messaging.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                circl_dev.twilio_messaging.models.shared.MessagingV1ServiceShortCode out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), circl_dev.twilio_messaging.models.shared.MessagingV1ServiceShortCode.class);
                res.messagingV1ServiceShortCode = out;
            }
        }

        return res;
    }

    public circl_dev.twilio_messaging.models.operations.DeleteShortCodeResponse deleteShortCode(circl_dev.twilio_messaging.models.operations.DeleteShortCodeRequest request, circl_dev.twilio_messaging.models.operations.DeleteShortCodeSecurity security) throws Exception {
        return this.deleteShortCode(request, security, null);
    }

    public circl_dev.twilio_messaging.models.operations.DeleteShortCodeResponse deleteShortCode(circl_dev.twilio_messaging.models.operations.DeleteShortCodeRequest request, circl_dev.twilio_messaging.models.operations.DeleteShortCodeSecurity security, String serverURL) throws Exception {
        String baseUrl = circl_dev.twilio_messaging.utils.Utils.templateUrl(DELETE_SHORT_CODE_SERVERS[0], new java.util.HashMap<String, String>());
        if (serverURL != null && !serverURL.isBlank()) {
            baseUrl = serverURL;
        }
        
        String url = circl_dev.twilio_messaging.utils.Utils.generateURL(circl_dev.twilio_messaging.models.operations.DeleteShortCodeRequest.class, baseUrl, "/v1/Services/{ServiceSid}/ShortCodes/{Sid}", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("DELETE");
        req.setURL(url);

        req.addHeader("Accept", "*/*");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        
        HTTPClient client = circl_dev.twilio_messaging.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        circl_dev.twilio_messaging.models.operations.DeleteShortCodeResponse res = new circl_dev.twilio_messaging.models.operations.DeleteShortCodeResponse(contentType, httpRes.statusCode()) {{
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 204) {
        }

        return res;
    }

    public circl_dev.twilio_messaging.models.operations.FetchShortCodeResponse fetchShortCode(circl_dev.twilio_messaging.models.operations.FetchShortCodeRequest request, circl_dev.twilio_messaging.models.operations.FetchShortCodeSecurity security) throws Exception {
        return this.fetchShortCode(request, security, null);
    }

    public circl_dev.twilio_messaging.models.operations.FetchShortCodeResponse fetchShortCode(circl_dev.twilio_messaging.models.operations.FetchShortCodeRequest request, circl_dev.twilio_messaging.models.operations.FetchShortCodeSecurity security, String serverURL) throws Exception {
        String baseUrl = circl_dev.twilio_messaging.utils.Utils.templateUrl(FETCH_SHORT_CODE_SERVERS[0], new java.util.HashMap<String, String>());
        if (serverURL != null && !serverURL.isBlank()) {
            baseUrl = serverURL;
        }
        
        String url = circl_dev.twilio_messaging.utils.Utils.generateURL(circl_dev.twilio_messaging.models.operations.FetchShortCodeRequest.class, baseUrl, "/v1/Services/{ServiceSid}/ShortCodes/{Sid}", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        
        HTTPClient client = circl_dev.twilio_messaging.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        circl_dev.twilio_messaging.models.operations.FetchShortCodeResponse res = new circl_dev.twilio_messaging.models.operations.FetchShortCodeResponse(contentType, httpRes.statusCode()) {{
            messagingV1ServiceShortCode = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (circl_dev.twilio_messaging.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                circl_dev.twilio_messaging.models.shared.MessagingV1ServiceShortCode out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), circl_dev.twilio_messaging.models.shared.MessagingV1ServiceShortCode.class);
                res.messagingV1ServiceShortCode = out;
            }
        }

        return res;
    }

    public circl_dev.twilio_messaging.models.operations.ListShortCodeResponse listShortCode(circl_dev.twilio_messaging.models.operations.ListShortCodeRequest request, circl_dev.twilio_messaging.models.operations.ListShortCodeSecurity security) throws Exception {
        return this.listShortCode(request, security, null);
    }

    public circl_dev.twilio_messaging.models.operations.ListShortCodeResponse listShortCode(circl_dev.twilio_messaging.models.operations.ListShortCodeRequest request, circl_dev.twilio_messaging.models.operations.ListShortCodeSecurity security, String serverURL) throws Exception {
        String baseUrl = circl_dev.twilio_messaging.utils.Utils.templateUrl(LIST_SHORT_CODE_SERVERS[0], new java.util.HashMap<String, String>());
        if (serverURL != null && !serverURL.isBlank()) {
            baseUrl = serverURL;
        }
        
        String url = circl_dev.twilio_messaging.utils.Utils.generateURL(circl_dev.twilio_messaging.models.operations.ListShortCodeRequest.class, baseUrl, "/v1/Services/{ServiceSid}/ShortCodes", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        java.util.List<NameValuePair> queryParams = circl_dev.twilio_messaging.utils.Utils.getQueryParams(circl_dev.twilio_messaging.models.operations.ListShortCodeRequest.class, request, null);
        if (queryParams != null) {
            for (NameValuePair queryParam : queryParams) {
                req.addQueryParam(queryParam);
            }
        }
        
        HTTPClient client = circl_dev.twilio_messaging.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        circl_dev.twilio_messaging.models.operations.ListShortCodeResponse res = new circl_dev.twilio_messaging.models.operations.ListShortCodeResponse(contentType, httpRes.statusCode()) {{
            listShortCodeResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (circl_dev.twilio_messaging.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                circl_dev.twilio_messaging.models.operations.ListShortCodeListShortCodeResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), circl_dev.twilio_messaging.models.operations.ListShortCodeListShortCodeResponse.class);
                res.listShortCodeResponse = out;
            }
        }

        return res;
    }
}