/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging;

import circl_dev.twilio_messaging.utils.HTTPClient;
import circl_dev.twilio_messaging.utils.HTTPRequest;
import circl_dev.twilio_messaging.utils.JSON;
import circl_dev.twilio_messaging.utils.SerializedBody;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.OffsetDateTime;
import org.apache.http.NameValuePair;

public class MessagingV1BrandRegistration {
	
    /**
	 * CREATE_BRAND_REGISTRATIONS_SERVERS contains the list of server urls available to the SDK.
	 */
    public static final String[] CREATE_BRAND_REGISTRATIONS_SERVERS = {
        "https://messaging.twilio.com",
    };
	
    /**
	 * FETCH_BRAND_REGISTRATIONS_SERVERS contains the list of server urls available to the SDK.
	 */
    public static final String[] FETCH_BRAND_REGISTRATIONS_SERVERS = {
        "https://messaging.twilio.com",
    };
	
    /**
	 * LIST_BRAND_REGISTRATIONS_SERVERS contains the list of server urls available to the SDK.
	 */
    public static final String[] LIST_BRAND_REGISTRATIONS_SERVERS = {
        "https://messaging.twilio.com",
    };
	
    /**
	 * UPDATE_BRAND_REGISTRATIONS_SERVERS contains the list of server urls available to the SDK.
	 */
    public static final String[] UPDATE_BRAND_REGISTRATIONS_SERVERS = {
        "https://messaging.twilio.com",
    };
	
	private SDKConfiguration sdkConfiguration;

	public MessagingV1BrandRegistration(SDKConfiguration sdkConfiguration) {
		this.sdkConfiguration = sdkConfiguration;
	}

    public circl_dev.twilio_messaging.models.operations.CreateBrandRegistrationsResponse createBrandRegistrations(circl_dev.twilio_messaging.models.operations.CreateBrandRegistrationsCreateBrandRegistrationsRequest request, circl_dev.twilio_messaging.models.operations.CreateBrandRegistrationsSecurity security) throws Exception {
        return this.createBrandRegistrations(request, security, null);
    }

    public circl_dev.twilio_messaging.models.operations.CreateBrandRegistrationsResponse createBrandRegistrations(circl_dev.twilio_messaging.models.operations.CreateBrandRegistrationsCreateBrandRegistrationsRequest request, circl_dev.twilio_messaging.models.operations.CreateBrandRegistrationsSecurity security, String serverURL) throws Exception {
        String baseUrl = circl_dev.twilio_messaging.utils.Utils.templateUrl(CREATE_BRAND_REGISTRATIONS_SERVERS[0], new java.util.HashMap<String, String>());
        if (serverURL != null && !serverURL.isBlank()) {
            baseUrl = serverURL;
        }
        
        String url = circl_dev.twilio_messaging.utils.Utils.generateURL(baseUrl, "/v1/a2p/BrandRegistrations");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        SerializedBody serializedRequestBody = circl_dev.twilio_messaging.utils.Utils.serializeRequestBody(request, "request", "form");
        req.setBody(serializedRequestBody);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        
        HTTPClient client = circl_dev.twilio_messaging.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        circl_dev.twilio_messaging.models.operations.CreateBrandRegistrationsResponse res = new circl_dev.twilio_messaging.models.operations.CreateBrandRegistrationsResponse(contentType, httpRes.statusCode()) {{
            messagingV1BrandRegistrations = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 201) {
            if (circl_dev.twilio_messaging.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                circl_dev.twilio_messaging.models.shared.MessagingV1BrandRegistrations out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), circl_dev.twilio_messaging.models.shared.MessagingV1BrandRegistrations.class);
                res.messagingV1BrandRegistrations = out;
            }
        }

        return res;
    }

    public circl_dev.twilio_messaging.models.operations.FetchBrandRegistrationsResponse fetchBrandRegistrations(circl_dev.twilio_messaging.models.operations.FetchBrandRegistrationsRequest request, circl_dev.twilio_messaging.models.operations.FetchBrandRegistrationsSecurity security) throws Exception {
        return this.fetchBrandRegistrations(request, security, null);
    }

    public circl_dev.twilio_messaging.models.operations.FetchBrandRegistrationsResponse fetchBrandRegistrations(circl_dev.twilio_messaging.models.operations.FetchBrandRegistrationsRequest request, circl_dev.twilio_messaging.models.operations.FetchBrandRegistrationsSecurity security, String serverURL) throws Exception {
        String baseUrl = circl_dev.twilio_messaging.utils.Utils.templateUrl(FETCH_BRAND_REGISTRATIONS_SERVERS[0], new java.util.HashMap<String, String>());
        if (serverURL != null && !serverURL.isBlank()) {
            baseUrl = serverURL;
        }
        
        String url = circl_dev.twilio_messaging.utils.Utils.generateURL(circl_dev.twilio_messaging.models.operations.FetchBrandRegistrationsRequest.class, baseUrl, "/v1/a2p/BrandRegistrations/{Sid}", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        
        HTTPClient client = circl_dev.twilio_messaging.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        circl_dev.twilio_messaging.models.operations.FetchBrandRegistrationsResponse res = new circl_dev.twilio_messaging.models.operations.FetchBrandRegistrationsResponse(contentType, httpRes.statusCode()) {{
            messagingV1BrandRegistrations = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (circl_dev.twilio_messaging.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                circl_dev.twilio_messaging.models.shared.MessagingV1BrandRegistrations out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), circl_dev.twilio_messaging.models.shared.MessagingV1BrandRegistrations.class);
                res.messagingV1BrandRegistrations = out;
            }
        }

        return res;
    }

    public circl_dev.twilio_messaging.models.operations.ListBrandRegistrationsResponse listBrandRegistrations(circl_dev.twilio_messaging.models.operations.ListBrandRegistrationsRequest request, circl_dev.twilio_messaging.models.operations.ListBrandRegistrationsSecurity security) throws Exception {
        return this.listBrandRegistrations(request, security, null);
    }

    public circl_dev.twilio_messaging.models.operations.ListBrandRegistrationsResponse listBrandRegistrations(circl_dev.twilio_messaging.models.operations.ListBrandRegistrationsRequest request, circl_dev.twilio_messaging.models.operations.ListBrandRegistrationsSecurity security, String serverURL) throws Exception {
        String baseUrl = circl_dev.twilio_messaging.utils.Utils.templateUrl(LIST_BRAND_REGISTRATIONS_SERVERS[0], new java.util.HashMap<String, String>());
        if (serverURL != null && !serverURL.isBlank()) {
            baseUrl = serverURL;
        }
        
        String url = circl_dev.twilio_messaging.utils.Utils.generateURL(baseUrl, "/v1/a2p/BrandRegistrations");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        java.util.List<NameValuePair> queryParams = circl_dev.twilio_messaging.utils.Utils.getQueryParams(circl_dev.twilio_messaging.models.operations.ListBrandRegistrationsRequest.class, request, null);
        if (queryParams != null) {
            for (NameValuePair queryParam : queryParams) {
                req.addQueryParam(queryParam);
            }
        }
        
        HTTPClient client = circl_dev.twilio_messaging.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        circl_dev.twilio_messaging.models.operations.ListBrandRegistrationsResponse res = new circl_dev.twilio_messaging.models.operations.ListBrandRegistrationsResponse(contentType, httpRes.statusCode()) {{
            listBrandRegistrationsResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (circl_dev.twilio_messaging.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                circl_dev.twilio_messaging.models.operations.ListBrandRegistrationsListBrandRegistrationsResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), circl_dev.twilio_messaging.models.operations.ListBrandRegistrationsListBrandRegistrationsResponse.class);
                res.listBrandRegistrationsResponse = out;
            }
        }

        return res;
    }

    public circl_dev.twilio_messaging.models.operations.UpdateBrandRegistrationsResponse updateBrandRegistrations(circl_dev.twilio_messaging.models.operations.UpdateBrandRegistrationsRequest request, circl_dev.twilio_messaging.models.operations.UpdateBrandRegistrationsSecurity security) throws Exception {
        return this.updateBrandRegistrations(request, security, null);
    }

    public circl_dev.twilio_messaging.models.operations.UpdateBrandRegistrationsResponse updateBrandRegistrations(circl_dev.twilio_messaging.models.operations.UpdateBrandRegistrationsRequest request, circl_dev.twilio_messaging.models.operations.UpdateBrandRegistrationsSecurity security, String serverURL) throws Exception {
        String baseUrl = circl_dev.twilio_messaging.utils.Utils.templateUrl(UPDATE_BRAND_REGISTRATIONS_SERVERS[0], new java.util.HashMap<String, String>());
        if (serverURL != null && !serverURL.isBlank()) {
            baseUrl = serverURL;
        }
        
        String url = circl_dev.twilio_messaging.utils.Utils.generateURL(circl_dev.twilio_messaging.models.operations.UpdateBrandRegistrationsRequest.class, baseUrl, "/v1/a2p/BrandRegistrations/{Sid}", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        
        HTTPClient client = circl_dev.twilio_messaging.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        circl_dev.twilio_messaging.models.operations.UpdateBrandRegistrationsResponse res = new circl_dev.twilio_messaging.models.operations.UpdateBrandRegistrationsResponse(contentType, httpRes.statusCode()) {{
            messagingV1BrandRegistrations = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 202) {
            if (circl_dev.twilio_messaging.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                circl_dev.twilio_messaging.models.shared.MessagingV1BrandRegistrations out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), circl_dev.twilio_messaging.models.shared.MessagingV1BrandRegistrations.class);
                res.messagingV1BrandRegistrations = out;
            }
        }

        return res;
    }
}