/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging;

import circl_dev.twilio_messaging.utils.HTTPClient;
import circl_dev.twilio_messaging.utils.HTTPRequest;
import circl_dev.twilio_messaging.utils.JSON;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;

public class MessagingV1LinkshorteningMessagingServiceDomainAssociation {
	
    /**
	 * FETCH_LINKSHORTENING_MESSAGING_SERVICE_DOMAIN_ASSOCIATION_SERVERS contains the list of server urls available to the SDK.
	 */
    public static final String[] FETCH_LINKSHORTENING_MESSAGING_SERVICE_DOMAIN_ASSOCIATION_SERVERS = {
        "https://messaging.twilio.com",
    };
	
	private SDKConfiguration sdkConfiguration;

	public MessagingV1LinkshorteningMessagingServiceDomainAssociation(SDKConfiguration sdkConfiguration) {
		this.sdkConfiguration = sdkConfiguration;
	}

    public circl_dev.twilio_messaging.models.operations.FetchLinkshorteningMessagingServiceDomainAssociationResponse fetchLinkshorteningMessagingServiceDomainAssociation(circl_dev.twilio_messaging.models.operations.FetchLinkshorteningMessagingServiceDomainAssociationRequest request, circl_dev.twilio_messaging.models.operations.FetchLinkshorteningMessagingServiceDomainAssociationSecurity security) throws Exception {
        return this.fetchLinkshorteningMessagingServiceDomainAssociation(request, security, null);
    }

    public circl_dev.twilio_messaging.models.operations.FetchLinkshorteningMessagingServiceDomainAssociationResponse fetchLinkshorteningMessagingServiceDomainAssociation(circl_dev.twilio_messaging.models.operations.FetchLinkshorteningMessagingServiceDomainAssociationRequest request, circl_dev.twilio_messaging.models.operations.FetchLinkshorteningMessagingServiceDomainAssociationSecurity security, String serverURL) throws Exception {
        String baseUrl = circl_dev.twilio_messaging.utils.Utils.templateUrl(FETCH_LINKSHORTENING_MESSAGING_SERVICE_DOMAIN_ASSOCIATION_SERVERS[0], new java.util.HashMap<String, String>());
        if (serverURL != null && !serverURL.isBlank()) {
            baseUrl = serverURL;
        }
        
        String url = circl_dev.twilio_messaging.utils.Utils.generateURL(circl_dev.twilio_messaging.models.operations.FetchLinkshorteningMessagingServiceDomainAssociationRequest.class, baseUrl, "/v1/LinkShortening/MessagingServices/{MessagingServiceSid}/Domain", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        
        HTTPClient client = circl_dev.twilio_messaging.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        circl_dev.twilio_messaging.models.operations.FetchLinkshorteningMessagingServiceDomainAssociationResponse res = new circl_dev.twilio_messaging.models.operations.FetchLinkshorteningMessagingServiceDomainAssociationResponse(contentType, httpRes.statusCode()) {{
            messagingV1LinkshorteningMessagingServiceDomainAssociation = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (circl_dev.twilio_messaging.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                circl_dev.twilio_messaging.models.shared.MessagingV1LinkshorteningMessagingServiceDomainAssociation out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), circl_dev.twilio_messaging.models.shared.MessagingV1LinkshorteningMessagingServiceDomainAssociation.class);
                res.messagingV1LinkshorteningMessagingServiceDomainAssociation = out;
            }
        }

        return res;
    }
}