/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging;

import circl_dev.twilio_messaging.utils.HTTPClient;
import circl_dev.twilio_messaging.utils.HTTPRequest;
import circl_dev.twilio_messaging.utils.JSON;
import circl_dev.twilio_messaging.utils.SerializedBody;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.OffsetDateTime;

public class MessagingV1DomainCerts {
	
    /**
	 * DELETE_DOMAIN_CERT_V4_SERVERS contains the list of server urls available to the SDK.
	 */
    public static final String[] DELETE_DOMAIN_CERT_V4_SERVERS = {
        "https://messaging.twilio.com",
    };
	
    /**
	 * FETCH_DOMAIN_CERT_V4_SERVERS contains the list of server urls available to the SDK.
	 */
    public static final String[] FETCH_DOMAIN_CERT_V4_SERVERS = {
        "https://messaging.twilio.com",
    };
	
    /**
	 * UPDATE_DOMAIN_CERT_V4_SERVERS contains the list of server urls available to the SDK.
	 */
    public static final String[] UPDATE_DOMAIN_CERT_V4_SERVERS = {
        "https://messaging.twilio.com",
    };
	
	private SDKConfiguration sdkConfiguration;

	public MessagingV1DomainCerts(SDKConfiguration sdkConfiguration) {
		this.sdkConfiguration = sdkConfiguration;
	}

    public circl_dev.twilio_messaging.models.operations.DeleteDomainCertV4Response deleteDomainCertV4(circl_dev.twilio_messaging.models.operations.DeleteDomainCertV4Request request, circl_dev.twilio_messaging.models.operations.DeleteDomainCertV4Security security) throws Exception {
        return this.deleteDomainCertV4(request, security, null);
    }

    public circl_dev.twilio_messaging.models.operations.DeleteDomainCertV4Response deleteDomainCertV4(circl_dev.twilio_messaging.models.operations.DeleteDomainCertV4Request request, circl_dev.twilio_messaging.models.operations.DeleteDomainCertV4Security security, String serverURL) throws Exception {
        String baseUrl = circl_dev.twilio_messaging.utils.Utils.templateUrl(DELETE_DOMAIN_CERT_V4_SERVERS[0], new java.util.HashMap<String, String>());
        if (serverURL != null && !serverURL.isBlank()) {
            baseUrl = serverURL;
        }
        
        String url = circl_dev.twilio_messaging.utils.Utils.generateURL(circl_dev.twilio_messaging.models.operations.DeleteDomainCertV4Request.class, baseUrl, "/v1/LinkShortening/Domains/{DomainSid}/Certificate", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("DELETE");
        req.setURL(url);

        req.addHeader("Accept", "*/*");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        
        HTTPClient client = circl_dev.twilio_messaging.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        circl_dev.twilio_messaging.models.operations.DeleteDomainCertV4Response res = new circl_dev.twilio_messaging.models.operations.DeleteDomainCertV4Response(contentType, httpRes.statusCode()) {{
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 204) {
        }

        return res;
    }

    public circl_dev.twilio_messaging.models.operations.FetchDomainCertV4Response fetchDomainCertV4(circl_dev.twilio_messaging.models.operations.FetchDomainCertV4Request request, circl_dev.twilio_messaging.models.operations.FetchDomainCertV4Security security) throws Exception {
        return this.fetchDomainCertV4(request, security, null);
    }

    public circl_dev.twilio_messaging.models.operations.FetchDomainCertV4Response fetchDomainCertV4(circl_dev.twilio_messaging.models.operations.FetchDomainCertV4Request request, circl_dev.twilio_messaging.models.operations.FetchDomainCertV4Security security, String serverURL) throws Exception {
        String baseUrl = circl_dev.twilio_messaging.utils.Utils.templateUrl(FETCH_DOMAIN_CERT_V4_SERVERS[0], new java.util.HashMap<String, String>());
        if (serverURL != null && !serverURL.isBlank()) {
            baseUrl = serverURL;
        }
        
        String url = circl_dev.twilio_messaging.utils.Utils.generateURL(circl_dev.twilio_messaging.models.operations.FetchDomainCertV4Request.class, baseUrl, "/v1/LinkShortening/Domains/{DomainSid}/Certificate", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        
        HTTPClient client = circl_dev.twilio_messaging.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        circl_dev.twilio_messaging.models.operations.FetchDomainCertV4Response res = new circl_dev.twilio_messaging.models.operations.FetchDomainCertV4Response(contentType, httpRes.statusCode()) {{
            messagingV1DomainCertV4 = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (circl_dev.twilio_messaging.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                circl_dev.twilio_messaging.models.shared.MessagingV1DomainCertV4 out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), circl_dev.twilio_messaging.models.shared.MessagingV1DomainCertV4.class);
                res.messagingV1DomainCertV4 = out;
            }
        }

        return res;
    }

    public circl_dev.twilio_messaging.models.operations.UpdateDomainCertV4Response updateDomainCertV4(circl_dev.twilio_messaging.models.operations.UpdateDomainCertV4Request request, circl_dev.twilio_messaging.models.operations.UpdateDomainCertV4Security security) throws Exception {
        return this.updateDomainCertV4(request, security, null);
    }

    public circl_dev.twilio_messaging.models.operations.UpdateDomainCertV4Response updateDomainCertV4(circl_dev.twilio_messaging.models.operations.UpdateDomainCertV4Request request, circl_dev.twilio_messaging.models.operations.UpdateDomainCertV4Security security, String serverURL) throws Exception {
        String baseUrl = circl_dev.twilio_messaging.utils.Utils.templateUrl(UPDATE_DOMAIN_CERT_V4_SERVERS[0], new java.util.HashMap<String, String>());
        if (serverURL != null && !serverURL.isBlank()) {
            baseUrl = serverURL;
        }
        
        String url = circl_dev.twilio_messaging.utils.Utils.generateURL(circl_dev.twilio_messaging.models.operations.UpdateDomainCertV4Request.class, baseUrl, "/v1/LinkShortening/Domains/{DomainSid}/Certificate", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        SerializedBody serializedRequestBody = circl_dev.twilio_messaging.utils.Utils.serializeRequestBody(request, "requestBody", "form");
        req.setBody(serializedRequestBody);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        
        HTTPClient client = circl_dev.twilio_messaging.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        circl_dev.twilio_messaging.models.operations.UpdateDomainCertV4Response res = new circl_dev.twilio_messaging.models.operations.UpdateDomainCertV4Response(contentType, httpRes.statusCode()) {{
            messagingV1DomainCertV4 = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200 || httpRes.statusCode() == 201) {
            if (circl_dev.twilio_messaging.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                circl_dev.twilio_messaging.models.shared.MessagingV1DomainCertV4 out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), circl_dev.twilio_messaging.models.shared.MessagingV1DomainCertV4.class);
                res.messagingV1DomainCertV4 = out;
            }
        }

        return res;
    }
}