/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging;

import circl_dev.twilio_messaging.utils.HTTPClient;
import circl_dev.twilio_messaging.utils.HTTPRequest;
import circl_dev.twilio_messaging.utils.JSON;
import circl_dev.twilio_messaging.utils.SerializedBody;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.OffsetDateTime;
import org.apache.http.NameValuePair;

public class MessagingV1AlphaSender {
	
    /**
	 * CREATE_ALPHA_SENDER_SERVERS contains the list of server urls available to the SDK.
	 */
    public static final String[] CREATE_ALPHA_SENDER_SERVERS = {
        "https://messaging.twilio.com",
    };
	
    /**
	 * DELETE_ALPHA_SENDER_SERVERS contains the list of server urls available to the SDK.
	 */
    public static final String[] DELETE_ALPHA_SENDER_SERVERS = {
        "https://messaging.twilio.com",
    };
	
    /**
	 * FETCH_ALPHA_SENDER_SERVERS contains the list of server urls available to the SDK.
	 */
    public static final String[] FETCH_ALPHA_SENDER_SERVERS = {
        "https://messaging.twilio.com",
    };
	
    /**
	 * LIST_ALPHA_SENDER_SERVERS contains the list of server urls available to the SDK.
	 */
    public static final String[] LIST_ALPHA_SENDER_SERVERS = {
        "https://messaging.twilio.com",
    };
	
	private SDKConfiguration sdkConfiguration;

	public MessagingV1AlphaSender(SDKConfiguration sdkConfiguration) {
		this.sdkConfiguration = sdkConfiguration;
	}

    public circl_dev.twilio_messaging.models.operations.CreateAlphaSenderResponse createAlphaSender(circl_dev.twilio_messaging.models.operations.CreateAlphaSenderRequest request, circl_dev.twilio_messaging.models.operations.CreateAlphaSenderSecurity security) throws Exception {
        return this.createAlphaSender(request, security, null);
    }

    public circl_dev.twilio_messaging.models.operations.CreateAlphaSenderResponse createAlphaSender(circl_dev.twilio_messaging.models.operations.CreateAlphaSenderRequest request, circl_dev.twilio_messaging.models.operations.CreateAlphaSenderSecurity security, String serverURL) throws Exception {
        String baseUrl = circl_dev.twilio_messaging.utils.Utils.templateUrl(CREATE_ALPHA_SENDER_SERVERS[0], new java.util.HashMap<String, String>());
        if (serverURL != null && !serverURL.isBlank()) {
            baseUrl = serverURL;
        }
        
        String url = circl_dev.twilio_messaging.utils.Utils.generateURL(circl_dev.twilio_messaging.models.operations.CreateAlphaSenderRequest.class, baseUrl, "/v1/Services/{ServiceSid}/AlphaSenders", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        SerializedBody serializedRequestBody = circl_dev.twilio_messaging.utils.Utils.serializeRequestBody(request, "requestBody", "form");
        req.setBody(serializedRequestBody);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        
        HTTPClient client = circl_dev.twilio_messaging.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        circl_dev.twilio_messaging.models.operations.CreateAlphaSenderResponse res = new circl_dev.twilio_messaging.models.operations.CreateAlphaSenderResponse(contentType, httpRes.statusCode()) {{
            messagingV1ServiceAlphaSender = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 201) {
            if (circl_dev.twilio_messaging.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                circl_dev.twilio_messaging.models.shared.MessagingV1ServiceAlphaSender out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), circl_dev.twilio_messaging.models.shared.MessagingV1ServiceAlphaSender.class);
                res.messagingV1ServiceAlphaSender = out;
            }
        }

        return res;
    }

    public circl_dev.twilio_messaging.models.operations.DeleteAlphaSenderResponse deleteAlphaSender(circl_dev.twilio_messaging.models.operations.DeleteAlphaSenderRequest request, circl_dev.twilio_messaging.models.operations.DeleteAlphaSenderSecurity security) throws Exception {
        return this.deleteAlphaSender(request, security, null);
    }

    public circl_dev.twilio_messaging.models.operations.DeleteAlphaSenderResponse deleteAlphaSender(circl_dev.twilio_messaging.models.operations.DeleteAlphaSenderRequest request, circl_dev.twilio_messaging.models.operations.DeleteAlphaSenderSecurity security, String serverURL) throws Exception {
        String baseUrl = circl_dev.twilio_messaging.utils.Utils.templateUrl(DELETE_ALPHA_SENDER_SERVERS[0], new java.util.HashMap<String, String>());
        if (serverURL != null && !serverURL.isBlank()) {
            baseUrl = serverURL;
        }
        
        String url = circl_dev.twilio_messaging.utils.Utils.generateURL(circl_dev.twilio_messaging.models.operations.DeleteAlphaSenderRequest.class, baseUrl, "/v1/Services/{ServiceSid}/AlphaSenders/{Sid}", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("DELETE");
        req.setURL(url);

        req.addHeader("Accept", "*/*");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        
        HTTPClient client = circl_dev.twilio_messaging.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        circl_dev.twilio_messaging.models.operations.DeleteAlphaSenderResponse res = new circl_dev.twilio_messaging.models.operations.DeleteAlphaSenderResponse(contentType, httpRes.statusCode()) {{
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 204) {
        }

        return res;
    }

    public circl_dev.twilio_messaging.models.operations.FetchAlphaSenderResponse fetchAlphaSender(circl_dev.twilio_messaging.models.operations.FetchAlphaSenderRequest request, circl_dev.twilio_messaging.models.operations.FetchAlphaSenderSecurity security) throws Exception {
        return this.fetchAlphaSender(request, security, null);
    }

    public circl_dev.twilio_messaging.models.operations.FetchAlphaSenderResponse fetchAlphaSender(circl_dev.twilio_messaging.models.operations.FetchAlphaSenderRequest request, circl_dev.twilio_messaging.models.operations.FetchAlphaSenderSecurity security, String serverURL) throws Exception {
        String baseUrl = circl_dev.twilio_messaging.utils.Utils.templateUrl(FETCH_ALPHA_SENDER_SERVERS[0], new java.util.HashMap<String, String>());
        if (serverURL != null && !serverURL.isBlank()) {
            baseUrl = serverURL;
        }
        
        String url = circl_dev.twilio_messaging.utils.Utils.generateURL(circl_dev.twilio_messaging.models.operations.FetchAlphaSenderRequest.class, baseUrl, "/v1/Services/{ServiceSid}/AlphaSenders/{Sid}", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        
        HTTPClient client = circl_dev.twilio_messaging.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        circl_dev.twilio_messaging.models.operations.FetchAlphaSenderResponse res = new circl_dev.twilio_messaging.models.operations.FetchAlphaSenderResponse(contentType, httpRes.statusCode()) {{
            messagingV1ServiceAlphaSender = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (circl_dev.twilio_messaging.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                circl_dev.twilio_messaging.models.shared.MessagingV1ServiceAlphaSender out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), circl_dev.twilio_messaging.models.shared.MessagingV1ServiceAlphaSender.class);
                res.messagingV1ServiceAlphaSender = out;
            }
        }

        return res;
    }

    public circl_dev.twilio_messaging.models.operations.ListAlphaSenderResponse listAlphaSender(circl_dev.twilio_messaging.models.operations.ListAlphaSenderRequest request, circl_dev.twilio_messaging.models.operations.ListAlphaSenderSecurity security) throws Exception {
        return this.listAlphaSender(request, security, null);
    }

    public circl_dev.twilio_messaging.models.operations.ListAlphaSenderResponse listAlphaSender(circl_dev.twilio_messaging.models.operations.ListAlphaSenderRequest request, circl_dev.twilio_messaging.models.operations.ListAlphaSenderSecurity security, String serverURL) throws Exception {
        String baseUrl = circl_dev.twilio_messaging.utils.Utils.templateUrl(LIST_ALPHA_SENDER_SERVERS[0], new java.util.HashMap<String, String>());
        if (serverURL != null && !serverURL.isBlank()) {
            baseUrl = serverURL;
        }
        
        String url = circl_dev.twilio_messaging.utils.Utils.generateURL(circl_dev.twilio_messaging.models.operations.ListAlphaSenderRequest.class, baseUrl, "/v1/Services/{ServiceSid}/AlphaSenders", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        java.util.List<NameValuePair> queryParams = circl_dev.twilio_messaging.utils.Utils.getQueryParams(circl_dev.twilio_messaging.models.operations.ListAlphaSenderRequest.class, request, null);
        if (queryParams != null) {
            for (NameValuePair queryParam : queryParams) {
                req.addQueryParam(queryParam);
            }
        }
        
        HTTPClient client = circl_dev.twilio_messaging.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        circl_dev.twilio_messaging.models.operations.ListAlphaSenderResponse res = new circl_dev.twilio_messaging.models.operations.ListAlphaSenderResponse(contentType, httpRes.statusCode()) {{
            listAlphaSenderResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (circl_dev.twilio_messaging.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                circl_dev.twilio_messaging.models.operations.ListAlphaSenderListAlphaSenderResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), circl_dev.twilio_messaging.models.operations.ListAlphaSenderListAlphaSenderResponse.class);
                res.listAlphaSenderResponse = out;
            }
        }

        return res;
    }
}