/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging;

import circl_dev.twilio_messaging.utils.HTTPClient;
import circl_dev.twilio_messaging.utils.HTTPRequest;
import circl_dev.twilio_messaging.utils.JSON;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import org.apache.http.NameValuePair;

public class MessagingV1UsAppToPersonUsecase {
	
    /**
	 * FETCH_US_APP_TO_PERSON_USECASE_SERVERS contains the list of server urls available to the SDK.
	 */
    public static final String[] FETCH_US_APP_TO_PERSON_USECASE_SERVERS = {
        "https://messaging.twilio.com",
    };
	
	private SDKConfiguration sdkConfiguration;

	public MessagingV1UsAppToPersonUsecase(SDKConfiguration sdkConfiguration) {
		this.sdkConfiguration = sdkConfiguration;
	}

    public circl_dev.twilio_messaging.models.operations.FetchUsAppToPersonUsecaseResponse fetchUsAppToPersonUsecase(circl_dev.twilio_messaging.models.operations.FetchUsAppToPersonUsecaseRequest request, circl_dev.twilio_messaging.models.operations.FetchUsAppToPersonUsecaseSecurity security) throws Exception {
        return this.fetchUsAppToPersonUsecase(request, security, null);
    }

    public circl_dev.twilio_messaging.models.operations.FetchUsAppToPersonUsecaseResponse fetchUsAppToPersonUsecase(circl_dev.twilio_messaging.models.operations.FetchUsAppToPersonUsecaseRequest request, circl_dev.twilio_messaging.models.operations.FetchUsAppToPersonUsecaseSecurity security, String serverURL) throws Exception {
        String baseUrl = circl_dev.twilio_messaging.utils.Utils.templateUrl(FETCH_US_APP_TO_PERSON_USECASE_SERVERS[0], new java.util.HashMap<String, String>());
        if (serverURL != null && !serverURL.isBlank()) {
            baseUrl = serverURL;
        }
        
        String url = circl_dev.twilio_messaging.utils.Utils.generateURL(circl_dev.twilio_messaging.models.operations.FetchUsAppToPersonUsecaseRequest.class, baseUrl, "/v1/Services/{MessagingServiceSid}/Compliance/Usa2p/Usecases", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        java.util.List<NameValuePair> queryParams = circl_dev.twilio_messaging.utils.Utils.getQueryParams(circl_dev.twilio_messaging.models.operations.FetchUsAppToPersonUsecaseRequest.class, request, null);
        if (queryParams != null) {
            for (NameValuePair queryParam : queryParams) {
                req.addQueryParam(queryParam);
            }
        }
        
        HTTPClient client = circl_dev.twilio_messaging.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        circl_dev.twilio_messaging.models.operations.FetchUsAppToPersonUsecaseResponse res = new circl_dev.twilio_messaging.models.operations.FetchUsAppToPersonUsecaseResponse(contentType, httpRes.statusCode()) {{
            messagingV1ServiceUsAppToPersonUsecase = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (circl_dev.twilio_messaging.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                circl_dev.twilio_messaging.models.shared.MessagingV1ServiceUsAppToPersonUsecase out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), circl_dev.twilio_messaging.models.shared.MessagingV1ServiceUsAppToPersonUsecase.class);
                res.messagingV1ServiceUsAppToPersonUsecase = out;
            }
        }

        return res;
    }
}