/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package circl_dev.twilio_messaging;

import circl_dev.twilio_messaging.utils.HTTPClient;
import circl_dev.twilio_messaging.utils.HTTPRequest;
import circl_dev.twilio_messaging.utils.JSON;
import circl_dev.twilio_messaging.utils.SerializedBody;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.OffsetDateTime;
import org.apache.http.NameValuePair;

public class MessagingV1BrandVetting {
	
    /**
	 * CREATE_BRAND_VETTING_SERVERS contains the list of server urls available to the SDK.
	 */
    public static final String[] CREATE_BRAND_VETTING_SERVERS = {
        "https://messaging.twilio.com",
    };
	
    /**
	 * FETCH_BRAND_VETTING_SERVERS contains the list of server urls available to the SDK.
	 */
    public static final String[] FETCH_BRAND_VETTING_SERVERS = {
        "https://messaging.twilio.com",
    };
	
    /**
	 * LIST_BRAND_VETTING_SERVERS contains the list of server urls available to the SDK.
	 */
    public static final String[] LIST_BRAND_VETTING_SERVERS = {
        "https://messaging.twilio.com",
    };
	
	private SDKConfiguration sdkConfiguration;

	public MessagingV1BrandVetting(SDKConfiguration sdkConfiguration) {
		this.sdkConfiguration = sdkConfiguration;
	}

    public circl_dev.twilio_messaging.models.operations.CreateBrandVettingResponse createBrandVetting(circl_dev.twilio_messaging.models.operations.CreateBrandVettingRequest request, circl_dev.twilio_messaging.models.operations.CreateBrandVettingSecurity security) throws Exception {
        return this.createBrandVetting(request, security, null);
    }

    public circl_dev.twilio_messaging.models.operations.CreateBrandVettingResponse createBrandVetting(circl_dev.twilio_messaging.models.operations.CreateBrandVettingRequest request, circl_dev.twilio_messaging.models.operations.CreateBrandVettingSecurity security, String serverURL) throws Exception {
        String baseUrl = circl_dev.twilio_messaging.utils.Utils.templateUrl(CREATE_BRAND_VETTING_SERVERS[0], new java.util.HashMap<String, String>());
        if (serverURL != null && !serverURL.isBlank()) {
            baseUrl = serverURL;
        }
        
        String url = circl_dev.twilio_messaging.utils.Utils.generateURL(circl_dev.twilio_messaging.models.operations.CreateBrandVettingRequest.class, baseUrl, "/v1/a2p/BrandRegistrations/{BrandSid}/Vettings", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        SerializedBody serializedRequestBody = circl_dev.twilio_messaging.utils.Utils.serializeRequestBody(request, "requestBody", "form");
        req.setBody(serializedRequestBody);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        
        HTTPClient client = circl_dev.twilio_messaging.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        circl_dev.twilio_messaging.models.operations.CreateBrandVettingResponse res = new circl_dev.twilio_messaging.models.operations.CreateBrandVettingResponse(contentType, httpRes.statusCode()) {{
            messagingV1BrandRegistrationsBrandVetting = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 201) {
            if (circl_dev.twilio_messaging.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                circl_dev.twilio_messaging.models.shared.MessagingV1BrandRegistrationsBrandVetting out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), circl_dev.twilio_messaging.models.shared.MessagingV1BrandRegistrationsBrandVetting.class);
                res.messagingV1BrandRegistrationsBrandVetting = out;
            }
        }

        return res;
    }

    public circl_dev.twilio_messaging.models.operations.FetchBrandVettingResponse fetchBrandVetting(circl_dev.twilio_messaging.models.operations.FetchBrandVettingRequest request, circl_dev.twilio_messaging.models.operations.FetchBrandVettingSecurity security) throws Exception {
        return this.fetchBrandVetting(request, security, null);
    }

    public circl_dev.twilio_messaging.models.operations.FetchBrandVettingResponse fetchBrandVetting(circl_dev.twilio_messaging.models.operations.FetchBrandVettingRequest request, circl_dev.twilio_messaging.models.operations.FetchBrandVettingSecurity security, String serverURL) throws Exception {
        String baseUrl = circl_dev.twilio_messaging.utils.Utils.templateUrl(FETCH_BRAND_VETTING_SERVERS[0], new java.util.HashMap<String, String>());
        if (serverURL != null && !serverURL.isBlank()) {
            baseUrl = serverURL;
        }
        
        String url = circl_dev.twilio_messaging.utils.Utils.generateURL(circl_dev.twilio_messaging.models.operations.FetchBrandVettingRequest.class, baseUrl, "/v1/a2p/BrandRegistrations/{BrandSid}/Vettings/{BrandVettingSid}", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        
        HTTPClient client = circl_dev.twilio_messaging.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        circl_dev.twilio_messaging.models.operations.FetchBrandVettingResponse res = new circl_dev.twilio_messaging.models.operations.FetchBrandVettingResponse(contentType, httpRes.statusCode()) {{
            messagingV1BrandRegistrationsBrandVetting = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (circl_dev.twilio_messaging.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                circl_dev.twilio_messaging.models.shared.MessagingV1BrandRegistrationsBrandVetting out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), circl_dev.twilio_messaging.models.shared.MessagingV1BrandRegistrationsBrandVetting.class);
                res.messagingV1BrandRegistrationsBrandVetting = out;
            }
        }

        return res;
    }

    public circl_dev.twilio_messaging.models.operations.ListBrandVettingResponse listBrandVetting(circl_dev.twilio_messaging.models.operations.ListBrandVettingRequest request, circl_dev.twilio_messaging.models.operations.ListBrandVettingSecurity security) throws Exception {
        return this.listBrandVetting(request, security, null);
    }

    public circl_dev.twilio_messaging.models.operations.ListBrandVettingResponse listBrandVetting(circl_dev.twilio_messaging.models.operations.ListBrandVettingRequest request, circl_dev.twilio_messaging.models.operations.ListBrandVettingSecurity security, String serverURL) throws Exception {
        String baseUrl = circl_dev.twilio_messaging.utils.Utils.templateUrl(LIST_BRAND_VETTING_SERVERS[0], new java.util.HashMap<String, String>());
        if (serverURL != null && !serverURL.isBlank()) {
            baseUrl = serverURL;
        }
        
        String url = circl_dev.twilio_messaging.utils.Utils.generateURL(circl_dev.twilio_messaging.models.operations.ListBrandVettingRequest.class, baseUrl, "/v1/a2p/BrandRegistrations/{BrandSid}/Vettings", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);

        req.addHeader("Accept", "application/json");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        java.util.List<NameValuePair> queryParams = circl_dev.twilio_messaging.utils.Utils.getQueryParams(circl_dev.twilio_messaging.models.operations.ListBrandVettingRequest.class, request, null);
        if (queryParams != null) {
            for (NameValuePair queryParam : queryParams) {
                req.addQueryParam(queryParam);
            }
        }
        
        HTTPClient client = circl_dev.twilio_messaging.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        circl_dev.twilio_messaging.models.operations.ListBrandVettingResponse res = new circl_dev.twilio_messaging.models.operations.ListBrandVettingResponse(contentType, httpRes.statusCode()) {{
            listBrandVettingResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (circl_dev.twilio_messaging.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                circl_dev.twilio_messaging.models.operations.ListBrandVettingListBrandVettingResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), circl_dev.twilio_messaging.models.operations.ListBrandVettingListBrandVettingResponse.class);
                res.listBrandVettingResponse = out;
            }
        }

        return res;
    }
}